"use client";
import {useEffect} from "react";
import DutchTutorV9 from "./DutchTutorV9";

const clean=(s:string)=>s.replace(/^[□✓]\s*/,"").trim();
function speakDutch(text:string){if(!text||typeof window==="undefined"||!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="nl-NL";u.rate=.82;const voices=window.speechSynthesis.getVoices();const nl=voices.find(v=>v.lang.toLowerCase().startsWith("nl"));if(nl)u.voice=nl;window.speechSynthesis.speak(u)}
function listenDutch(target:string,host:HTMLElement){const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){host.textContent="Use your keyboard microphone, then compare what it heard.";host.dataset.kind="info";return}const r=new SR();r.lang="nl-NL";r.interimResults=false;r.maxAlternatives=3;host.textContent="Listening…";host.dataset.kind="listen";r.onresult=(e:any)=>{const heard=Array.from(e.results[0]||[]).map((x:any)=>x.transcript);const n=(x:string)=>x.toLocaleLowerCase("nl-NL").replace(/[.!?,:'’\"“”]/g,"").replace(/\s+/g," ").trim();const ok=heard.some((x:string)=>n(x)===n(target));host.textContent=ok?`✓ Heard: ${heard[0]}`:`Heard: ${heard[0]} · Listen once more, then repeat.`;host.dataset.kind=ok?"good":"retry"};r.onerror=()=>{host.textContent="Couldn’t hear that clearly — try again.";host.dataset.kind="retry"};r.start()}
function controls(target:string){const box=document.createElement("div");box.className="pronounceControls";box.dataset.pronounce="1";const hear=document.createElement("button");hear.type="button";hear.className="pronounceButton hear";hear.innerHTML="<span>🔊</span><small>Hear</small>";hear.onclick=()=>speakDutch(target);const practice=document.createElement("button");practice.type="button";practice.className="pronounceButton practice";practice.innerHTML="<small>Practice</small><span>🎙️</span>";const feedback=document.createElement("div");feedback.className="pronounceFeedback";practice.onclick=()=>listenDutch(target,feedback);box.append(hear,practice,feedback);return box}
function isLikelyDutch(text:string){return !!text&&text.length<140&&!/^(Vocabulary|Phrases|Grammar|Notebook|Pattern|Lesson|Quick|What|Write|Say|How|Who|Where|Nice|My name|And you|I )\b/i.test(text)}
export default function DutchTutorV10(){useEffect(()=>{let timer:any;const enhance=()=>{const headings=[...document.querySelectorAll("h3")];const lessonRoot=headings.find(h=>h.textContent?.includes("1. Vocabulary"))?.parentElement?.parentElement;if(!lessonRoot)return;for(const section of [...lessonRoot.querySelectorAll("section.card")]){const h=section.querySelector("h3")?.textContent||"";if(!/1\. Vocabulary|2\. Phrases|3\. Grammar/.test(h))continue;const candidates=[...section.querySelectorAll(".mistake > strong,.scoreRow strong,p > strong,.success > strong")];for(const el of candidates){const node=el as HTMLElement;if(node.parentElement?.querySelector(":scope > .pronounceControls"))continue;let target=clean(node.textContent||"");if(target==="Pattern:"){const parent=node.parentElement;target=clean((parent?.textContent||"").replace(/^Pattern:\s*/,""))}if(!isLikelyDutch(target))continue;node.parentElement?.appendChild(controls(target))}}
const notebook=headings.find(h=>h.textContent?.startsWith("4. Notebook"))?.parentElement;if(notebook&&!notebook.querySelector(".notebookGuide")){const guide=document.createElement("div");guide.className="notebookGuide";guide.innerHTML="<strong>✍️ Write for understanding, not copying</strong><span>Each task includes English so you know exactly what you are putting on paper. Say the Dutch aloud as you write it. The digital review below makes you retrieve it without simply copying.</span>";notebook.insertBefore(guide,notebook.querySelector("p"))}
};const observer=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(enhance,80)});observer.observe(document.body,{childList:true,subtree:true});enhance();return()=>{observer.disconnect();clearTimeout(timer)}},[]);return <DutchTutorV9/>}
