"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import DutchTutorV5 from "./DutchTutorV5";

type Tab="today"|"speak"|"youtube"|"immerse"|"progress";
type SpeakMode="guided"|"scenario"|"drill"|"read";
type Chat={role:"assistant"|"user";text:string;translation?:string;correction?:{wrong:string;better:string;why:string}};
type Daily={date:string;youtube:boolean;app:boolean;speak:boolean;immersion:boolean;practiceMinutes:number;speakingMinutes:number;listeningMinutes:number};
type V7State={version:7;youtubeLesson:number;youtubeTotal:number;youtubeLevel:string;daily:Daily;speakingSessions:number;speakingTurns:number;recentActivity:string[];savedVideos:{id:string;title:string;url:string;listened:boolean}[]};
const KEY="dutch-hybrid-v7";
const d=()=>new Date().toISOString().slice(0,10);
const init:V7State={version:7,youtubeLesson:0,youtubeTotal:30,youtubeLevel:"A0",daily:{date:d(),youtube:false,app:false,speak:false,immersion:false,practiceMinutes:0,speakingMinutes:0,listeningMinutes:0},speakingSessions:0,speakingTurns:0,recentActivity:[],savedVideos:[]};
const scenarios=["Meeting someone","Ordering food","Going to a store","Talking about school","Talking about sports","Talking about family","Talking about my day","Traveling","Asking directions","Making plans"];
const drills=["Say: I have class today.","Say: I am tired, but I am doing well.","Say: I am going to practice later.","Say: I want to learn Dutch.","Say: Where are you?","Say: I don't understand."];
const readLines=["Hoi! Hoe gaat het vandaag?","Ik heb vandaag les en ik ga straks trainen.","Ik leer Nederlands omdat ik het leuk vind.","Morgen ga ik naar de les en daarna doe ik mijn huiswerk."];
function roll(s:V7State):V7State{return s.daily?.date===d()?s:{...s,daily:{date:d(),youtube:false,app:false,speak:false,immersion:false,practiceMinutes:0,speakingMinutes:0,listeningMinutes:0}}}
function readV5(){try{return JSON.parse(localStorage.getItem("dutch-tutor-progress-v5")||"null")}catch{return null}}
export default function DutchTutorV7(){
 const [state,setState]=useState<V7State>(init);const [tab,setTab]=useState<Tab>("today");const [lessonMode,setLessonMode]=useState(false);const [requested,setRequested]=useState(10);const [loaded,setLoaded]=useState(false);const [v5,setV5]=useState<any>(null);
 const [speakMode,setSpeakMode]=useState<SpeakMode>("guided");const [scenario,setScenario]=useState(scenarios[0]);const [chat,setChat]=useState<Chat[]>([]);const [input,setInput]=useState("");const [busy,setBusy]=useState(false);const [drillIndex,setDrillIndex]=useState(0);const [readIndex,setReadIndex]=useState(0);const [speechResult,setSpeechResult]=useState("");const [video,setVideo]=useState({title:"",url:""});
 useEffect(()=>{try{const x=localStorage.getItem(KEY);setState(roll(x?{...init,...JSON.parse(x)}:init))}catch{setState(init)}setV5(readV5());setLoaded(true)},[]);
 useEffect(()=>{if(loaded)localStorage.setItem(KEY,JSON.stringify(state))},[state,loaded]);
 const vocab=v5?.vocabulary||[];const weak=vocab.filter((x:any)=>x.mastery<50||x.wrongRecall>x.correctRecall);const strong=vocab.filter((x:any)=>x.mastery>=70);const quizAvg=v5?.recentScores?.length?Math.round(v5.recentScores.reduce((a:number,b:number)=>a+b,0)/v5.recentScores.length):0;const dailyDone=[state.daily.youtube,state.daily.app,state.daily.speak,state.daily.immersion].filter(Boolean).length;
 function patchDaily(p:Partial<Daily>){setState(s=>({...s,daily:{...s.daily,...p}}))}
 function openLesson(min:number){setRequested(min);patchDaily({app:true,practiceMinutes:state.daily.practiceMinutes+min});setState(s=>({...s,recentActivity:[`${min}-minute app lesson started`,...s.recentActivity].slice(0,12)}));setLessonMode(true)}
 function markYouTube(){setState(s=>({...s,youtubeLesson:s.youtubeLesson+1,daily:{...s.daily,youtube:true},recentActivity:[`Kim lesson ${s.youtubeLesson+1} completed`,...s.recentActivity].slice(0,12)}))}
 function knownList(){return vocab.slice(-160).map((x:any)=>`${x.dutch}${x.english?` = ${x.english}`:""}`)}
 function beginSpeak(mode:SpeakMode){setSpeakMode(mode);setSpeechResult("");setTab("speak");setChat([]);if(mode==="guided")setChat([{role:"assistant",text:"Hoi! Hoe gaat het vandaag?",translation:"Hi! How are you today?"}]);if(mode==="scenario")setChat([{role:"assistant",text:`We oefenen: ${scenario}. Ik begin eenvoudig. Hoi!`,translation:`We are practicing: ${scenario}. I’ll start simply. Hi!`}])}
 async function send(e?:FormEvent,forced?:string){e?.preventDefault();const text=(forced??input).trim();if(!text||busy)return;setInput("");setChat(c=>[...c,{role:"user",text}]);setBusy(true);try{const r=await fetch("/api/tutor",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text,history:chat,minutes:10,immersionLevel:1,knownWords:knownList(),weakWords:weak.slice(0,25).map((x:any)=>x.dutch),focusWords:vocab.slice(-12).map((x:any)=>x.dutch),commonMistakes:v5?.commonMistakes||[],speakingMode:speakMode,scenario:speakMode==="scenario"?scenario:""})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Tutor error");setChat(c=>[...c,{role:"assistant",text:x.reply,translation:x.translation,correction:x.correction||undefined}]);setState(s=>({...s,speakingTurns:s.speakingTurns+1,daily:{...s.daily,speak:true,speakingMinutes:s.daily.speakingMinutes+1}}));}catch(err){setChat(c=>[...c,{role:"assistant",text:err instanceof Error?err.message:"Tutor error"}])}finally{setBusy(false)}}
 function listen(text:string){if(!("speechSynthesis" in window))return;const u=new SpeechSynthesisUtterance(text);u.lang="nl-NL";speechSynthesis.cancel();speechSynthesis.speak(u)}
 function mic(onText?:(t:string)=>void){const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){alert("Browser speech recognition is unavailable. Use the keyboard microphone instead.");return}const r=new SR();r.lang="nl-NL";r.interimResults=false;r.onresult=(e:any)=>{const t=e.results[0][0].transcript;onText?onText(t):setInput(t)};r.start()}
 function finishSpeaking(){setState(s=>({...s,speakingSessions:s.speakingSessions+1,daily:{...s.daily,speak:true},recentActivity:[`${speakMode} speaking practice`,...s.recentActivity].slice(0,12)}));setTab("today")}
 if(!loaded)return null;
 if(lessonMode)return <><button className="floatingBack" onClick={()=>{setLessonMode(false);setV5(readV5())}}>← Back to Today</button><div className="lessonNotice">You chose about {requested} min. Use the closest session length in the lesson screen.</div><DutchTutorV5/></>;
 return <main className="shell"><header className="header"><div><div className="brand">Dutch Tutor 🇳🇱</div><div className="subtle">YouTube structure · flexible app practice · real speaking</div></div><span className="badge">{state.youtubeLevel}</span></header>
 {tab==="today"&&<div className="stack"><section className="card hero"><div className="kicker">TODAY</div><h1>Do the Dutch that fits your day.</h1><div className="progressBar"><span style={{width:`${dailyDone*25}%`}}/></div><div className="subtle">{dailyDone}/4 parts touched today. No streak pressure.</div></section><section className="card taskCard"><div className="taskCheck">{state.daily.youtube?"✓":"□"}</div><div><strong>MAIN LESSON</strong><p className="subtle">Watch the next Dutchies to Be / Learn Dutch with Kim lesson.</p><div className="row"><span className="badge">{state.youtubeLevel} · lesson {state.youtubeLesson}/{state.youtubeTotal}</span><button className="secondary" onClick={markYouTube}>{state.daily.youtube?"Mark another":"Mark complete"}</button></div></div></section><section className="card"><div className="kicker">APP PRACTICE</div><strong>How much time do you have?</strong><div className="timeGrid5">{[5,10,15,20,30].map(m=><button key={m} className="timeButton" onClick={()=>openLesson(m)}><strong>{m}</strong><span>{m===30?"min+":"min"}</span></button>)}</div><p className="subtle">This opens the existing lesson engine with recall, vocabulary, sentence work, conversation, corrections, quiz repair, and spaced review.</p></section><section className="card taskCard" onClick={()=>beginSpeak("guided")}><div className="taskCheck">{state.daily.speak?"✓":"□"}</div><div><strong>SPEAK</strong><p className="subtle">5–10 minutes. Use the microphone and physically produce Dutch.</p></div></section><section className="card taskCard" onClick={()=>setTab("immerse")}><div className="taskCheck">{state.daily.immersion?"✓":"□"}</div><div><strong>IMMERSION</strong><p className="subtle">Listen while walking, eating, getting ready, or between classes.</p></div></section></div>}
 {tab==="speak"&&<div className="stack"><section className="card"><div className="kicker">SPEAKING</div><div className="modeGrid">{(["guided","scenario","drill","read"] as SpeakMode[]).map(m=><button className={speakMode===m?"secondary activeMode":"secondary"} onClick={()=>beginSpeak(m)} key={m}>{m==="guided"?"Guided":m==="scenario"?"Scenarios":m==="drill"?"Drills":"Read aloud"}</button>)}</div>{speakMode==="scenario"&&<select className="bigInput" value={scenario} onChange={e=>setScenario(e.target.value)}>{scenarios.map(x=><option key={x}>{x}</option>)}</select>}</section>
 {(speakMode==="guided"||speakMode==="scenario")&&<><div className="chat">{chat.map((m,i)=><div key={i}><div className={`bubble ${m.role==="assistant"?"tutor":"user"}`}>{m.text}</div>{m.role==="assistant"&&<div className="messageTools"><button onClick={()=>listen(m.text)}>🔊 Listen</button>{m.translation&&<span className="helper">{m.translation}</span>}</div>}{m.correction&&<div className="correction"><strong>Better:</strong> {m.correction.better}<small>{m.correction.why}</small><button className="secondary" onClick={()=>listen(m.correction!.better)}>🔊 Hear correction</button></div>}</div>)}</div><form className="composer" onSubmit={send}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Speak first; typing is backup…"/><button type="button" className="iconButton mic" onClick={()=>mic()}>🎙</button><button className="iconButton" disabled={busy}>↑</button></form></>}
 {speakMode==="drill"&&<section className="card recallCard"><div className="kicker">SPEAKING DRILL {drillIndex+1}/{drills.length}</div><h2>{drills[drillIndex]}</h2><button className="primary" onClick={()=>mic(t=>{setSpeechResult(t);setInput(t)})}>🎙 Speak answer</button>{speechResult&&<div className="success"><strong>Heard:</strong> {speechResult}<button className="primary compact" onClick={()=>{void send(undefined,speechResult);setDrillIndex(i=>(i+1)%drills.length);setSpeechResult("")}}>Evaluate & next</button></div>}</section>}
 {speakMode==="read"&&<section className="card recallCard"><div className="kicker">READ ALOUD</div><h2>{readLines[readIndex]}</h2><button className="secondary" onClick={()=>listen(readLines[readIndex])}>🔊 Hear native-style TTS</button><button className="primary" onClick={()=>mic(t=>setSpeechResult(t))}>🎙 Read it aloud</button>{speechResult&&<div className="success"><strong>Speech recognition heard:</strong> {speechResult}<p className="subtle">This checks whether Dutch speech recognition can understand you; it is not phoneme-level pronunciation scoring.</p><button className="secondary" onClick={()=>{setReadIndex(i=>(i+1)%readLines.length);setSpeechResult("")}}>Next sentence</button></div>}</section>}<button className="secondary" onClick={finishSpeaking}>Finish speaking practice</button></div>}
 {tab==="youtube"&&<div className="stack"><section className="card"><div className="kicker">MAIN DUTCH COURSE</div><h2 className="noTopish">Dutchies to Be / Learn Dutch with Kim</h2><p className="subtle">Keep this frictionless. Watch the next lesson in order and use paper notes if you want.</p><div className="stats"><div className="stat"><strong>{state.youtubeLesson}</strong><span>current lesson</span></div><div className="stat"><strong>{state.youtubeLevel}</strong><span>course level</span></div></div><button className="primary" onClick={markYouTube}>✓ Main lesson completed today</button><div className="row" style={{marginTop:12}}><select className="bigInput" value={state.youtubeLevel} onChange={e=>setState(s=>({...s,youtubeLevel:e.target.value}))}>{["A0","A1","A2","B1","B2"].map(x=><option key={x}>{x}</option>)}</select><input className="bigInput" type="number" min="0" value={state.youtubeLesson} onChange={e=>setState(s=>({...s,youtubeLesson:Number(e.target.value)}))}/></div></section><form className="card stack" onSubmit={e=>{e.preventDefault();if(!video.title.trim())return;setState(s=>({...s,savedVideos:[...s.savedVideos,{id:`v-${Date.now()}`,title:video.title,url:video.url,listened:false}]}));setVideo({title:"",url:""})}}><div className="kicker">OPTIONAL</div><strong>Save a video</strong><input className="bigInput" placeholder="Title" value={video.title} onChange={e=>setVideo({...video,title:e.target.value})}/><input className="bigInput" placeholder="YouTube link" value={video.url} onChange={e=>setVideo({...video,url:e.target.value})}/><button className="secondary">Save video</button></form></div>}
 {tab==="immerse"&&<div className="stack"><section className="card"><div className="kicker">IMMERSION</div><h2 className="noTopish">Keep Dutch in your ears.</h2><p className="subtle">Supplemental. It never replaces your structured course or app practice.</p><div className="row"><button className="secondary" onClick={()=>patchDaily({immersion:true,listeningMinutes:state.daily.listeningMinutes+20})}>+20 min</button><strong>{state.daily.listeningMinutes} min today</strong></div></section><section className="card"><strong>Good background source</strong><p className="subtle">Learn Dutch with Kim / Dutchies to Be beginner playlists and comprehensible listening you can follow without watching constantly.</p><a href="https://www.youtube.com/@learndutchwithkim" target="_blank" rel="noreferrer">Open channel ↗</a></section>{state.savedVideos.map(v=><section className="card" key={v.id}><div className="row"><div><strong>{v.title}</strong><div className="subtle">{v.listened?"Listened":"Saved"}</div></div>{v.url&&<a href={v.url} target="_blank" rel="noreferrer">Open ↗</a>}</div></section>)}</div>}
 {tab==="progress"&&<div className="stack"><section className="card"><div className="kicker">PROGRESS</div><h2 className="noTopish">A0 → A1 → A2 → B1 → B2</h2><p className="subtle">Meaningful learning metrics, not streaks.</p></section><div className="stats"><Stat n={v5?.sessions||0} t="App lessons"/><Stat n={vocab.length} t="Vocabulary tracked"/><Stat n={strong.length} t="Strong chunks"/><Stat n={`${quizAvg||0}%`} t="Quiz average"/><Stat n={state.speakingSessions} t="Speaking sessions"/><Stat n={weak.length} t="Problem items"/></div><section className="card"><strong>Recent activity</strong>{state.recentActivity.length?state.recentActivity.map((x,i)=><div className="scoreRow" key={i}>{x}</div>):<p className="subtle">Practice will appear here as you use the app.</p>}</section></div>}
 <nav className="nav nav5">{(["today","youtube","speak","immerse","progress"] as Tab[]).map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x==="today"?"Today":x==="youtube"?"Course":x[0].toUpperCase()+x.slice(1)}</button>)}</nav></main>
}
function Stat({n,t}:{n:string|number;t:string}){return <div className="stat"><strong>{n}</strong><span>{t}</span></div>}
