"use client";

import { useEffect, useMemo, useState } from "react";
import DutchTutorV8 from "./DutchTutorV8";

type RescueItem={id:string;prompt:string;answer:string;source:string;strength:number;nextReview:string;correct:number;wrong:number};
type RescueState={version:9;items:RescueItem[];quickReviews:number;lastQuickReview?:string;todayReviewed:number;todayDate:string};
const KEY="dutch-tutor-v9-retention";
const V8_KEY="dutch-tutor-v8";
const V5_KEY="dutch-tutor-progress-v5";
const today=()=>new Date().toISOString().slice(0,10);
const addDays=(n:number)=>{const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const normalize=(s:string)=>s.toLocaleLowerCase("nl-NL").trim().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[.!?,:'’\"“”]/g,"").replace(/\s+/g," ");
function distance(a:string,b:string){const p=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let left=i,diag=i-1;for(let j=1;j<=b.length;j++){const up=p[j];const cur=a[i-1]===b[j-1]?diag:1+Math.min(diag,up,left);p[j]=cur;diag=up;left=cur}}return p[b.length]}
function matches(a:string,b:string){const x=normalize(a),y=normalize(b);if(!x||!y)return false;if(x===y||x.replace(/\s/g,"")===y.replace(/\s/g,""))return true;const tolerance=y.length>=18?2:y.length>=7?1:0;return Math.abs(x.length-y.length)<=tolerance&&distance(x,y)<=tolerance}
function readJSON(key:string){try{return JSON.parse(localStorage.getItem(key)||"null")}catch{return null}}
function collectMaterial():RescueItem[]{const out:RescueItem[]=[];const seen=new Set<string>();const add=(prompt:string,answer:string,source:string,id:string)=>{if(!answer||answer.includes("…")||answer.includes("..."))return;const k=normalize(answer);if(!k||seen.has(k))return;seen.add(k);out.push({id,prompt,answer,source,strength:0,nextReview:today(),correct:0,wrong:0})};const v8=readJSON(V8_KEY);for(const c of v8?.completed||[]){const n=c?.number||"?",l=c?.lesson||{};for(let i=0;i<(l.vocabulary||[]).length;i++){const v=l.vocabulary[i];add(`How do you say “${v.english}” in Dutch?`,v.dutch,`Lesson ${n}`,`v8-${n}-v-${i}`)}for(let i=0;i<(l.phrases||[]).length;i++){const p=l.phrases[i];add(`Say the phrase: “${p.english}”`,p.dutch,`Lesson ${n}`,`v8-${n}-p-${i}`)}if(l.grammar?.pattern)add(`Recall the grammar pattern from ${l.grammar.title}.`,l.grammar.pattern,`Lesson ${n}`,`v8-${n}-g`)}const v5=readJSON(V5_KEY);for(const w of v5?.vocabulary||[]){add(`How do you say “${w.english}” in Dutch?`,w.dutch,"Earlier app practice",`v5-${w.id||normalize(w.dutch)}`)}return out}
function mergeItems(saved:RescueItem[],fresh:RescueItem[]){const map=new Map(saved.map(x=>[x.id,x]));return fresh.map(x=>map.has(x.id)?{...x,...map.get(x.id)!}:x)}
function schedule(item:RescueItem,ok:boolean){const steps=[1,3,7,14,30,60,120];const strength=ok?Math.min(6,item.strength+1):Math.max(0,item.strength-1);return{...item,strength,nextReview:addDays(ok?steps[strength]:1),correct:item.correct+(ok?1:0),wrong:item.wrong+(ok?0:1)}}
export default function DutchTutorV9(){const[retention,setRetention]=useState<RescueState>({version:9,items:[],quickReviews:0,todayReviewed:0,todayDate:today()});const[open,setOpen]=useState(false);const[index,setIndex]=useState(0);const[input,setInput]=useState("");const[checked,setChecked]=useState(false);const[wasCorrect,setWasCorrect]=useState(false);const[loaded,setLoaded]=useState(false);
useEffect(()=>{const fresh=collectMaterial();const saved=readJSON(KEY);const base:RescueState=saved?{version:9,items:mergeItems(saved.items||[],fresh),quickReviews:saved.quickReviews||0,lastQuickReview:saved.lastQuickReview,todayReviewed:saved.todayDate===today()?saved.todayReviewed||0:0,todayDate:today()}:{version:9,items:fresh,quickReviews:0,todayReviewed:0,todayDate:today()};setRetention(base);setLoaded(true)},[]);
useEffect(()=>{if(loaded)localStorage.setItem(KEY,JSON.stringify(retention))},[retention,loaded]);
const due=useMemo(()=>retention.items.filter(x=>x.nextReview<=today()).sort((a,b)=>(b.wrong-b.correct)-(a.wrong-a.correct)||a.strength-b.strength),[retention.items]);const session=useMemo(()=>{const dueNow=due.slice(0,5);if(dueNow.length>=5)return dueNow;const fallback=retention.items.filter(x=>!dueNow.some(d=>d.id===x.id)).sort((a,b)=>a.strength-b.strength).slice(0,5-dueNow.length);return [...dueNow,...fallback]},[due,retention.items]);const item=session[index];
function start(){const fresh=collectMaterial();setRetention(s=>({...s,items:mergeItems(s.items,fresh)}));setIndex(0);setInput("");setChecked(false);setOpen(true)}
function check(){if(!item||!input.trim())return;setWasCorrect(matches(input,item.answer));setChecked(true)}
function next(){if(!item)return;setRetention(s=>({...s,items:s.items.map(x=>x.id===item.id?schedule(x,wasCorrect):x),todayReviewed:s.todayReviewed+1,todayDate:today()}));setInput("");setChecked(false);if(index>=session.length-1){setRetention(s=>({...s,quickReviews:s.quickReviews+1,lastQuickReview:today()}));setOpen(false);setIndex(0)}else setIndex(i=>i+1)}
return <><DutchTutorV8/><button className="rescueFab" onClick={start}><span className="rescueIcon">⚡</span><span><strong>Too busy?</strong><small>3-min review</small></span>{due.length>0&&<b>{due.length}</b>}</button>{open&&<div className="rescueBackdrop" onClick={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="rescueSheet"><div className="rescueFlag" aria-hidden="true"><span></span><span></span><span></span></div><div className="row"><div><div className="kicker">CONSISTENCY RESCUE</div><h2 className="noTopish">Three minutes still counts.</h2></div><button className="rescueClose" onClick={()=>setOpen(false)}>×</button></div>{!item?<div className="rescueEmpty"><div className="rescueGraphic">🇳🇱</div><strong>No learned material yet.</strong><p className="subtle">Complete your first lesson, then this button becomes a fast recall session for busy days.</p></div>:<><div className="rescueMeta"><span>{index+1}/{session.length}</span><span>{item.source}</span><span>{due.length} due</span></div><div className="rescuePrompt"><div className="rescueGraphic">🧠</div><h3>{item.prompt}</h3><p className="subtle">Say it aloud first. Then type what you remember. No hints before retrieval.</p></div><input className="bigInput" autoFocus value={input} onChange={e=>{setInput(e.target.value);setChecked(false)}} placeholder="Dutch from memory…" onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();checked?next():check()}}}/>{!checked?<button className="primary" disabled={!input.trim()} onClick={check}>Check from memory</button>:<div className={wasCorrect?"success":"rescueMiss"}><strong>{wasCorrect?"✓ Retrieved":"Not yet — repair it"}</strong><div className="rescueAnswer">{item.answer}</div><p className="subtle">{wasCorrect?"Good. This item earns a longer gap before it returns.":"Read it once, say it aloud, then write it in your notebook if it keeps missing. It returns sooner."}</p><button className="primary" onClick={next}>{index>=session.length-1?"Finish rescue":"Next"}</button></div>}</>}</section></div>}</>}
