"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";

type Tab = "home"|"learn"|"review"|"quiz"|"progress";
type Stage = "teach"|"review"|"conversation";
type Correction = { wrong:string; better:string; why:string; clue?:string };
type LearnedChunk = { dutch:string; english:string; pronunciation:string; memoryHook?:string };
type ChatMessage = { role:"assistant"|"user"; text:string; translation?:string; hint?:string; correction?:Correction; retryRequired?:boolean };
type VocabularyWord = { id:string; dutch:string; english:string; pronunciation:string; memoryHook?:string; mastery:number; correctRecall:number; wrongRecall:number; correctUse:number; wrongUse:number; nextReview:string; lastSeen?:string };
type CurriculumItem = LearnedChunk & { id:string; exampleDutch:string; exampleEnglish:string; topic:string };
type QuizQuestion = { id:string; part:1|2|3|4|5; prompt:string; word?:string; tokens?:string[] };
type QuizGrade = { score:number; items:{id:string;correct:boolean;points:number;correction?:string;explanation?:string}[]; coachNote?:string };
type ProgressState = { version:4; wordsLearned:number; lastQuiz:number; sessions:number; vocabulary:VocabularyWord[]; recentScores:number[]; commonMistakes:{wrong:string;correct:string;why?:string}[] };
type ActiveMode = "learn"|"quiz";
type SavedSession = {
  savedAt:number; activeMode:ActiveMode; minutes:number; stage:Stage; messages:ChatMessage[]; turns:number; pendingRetry:Correction|null;
  lessonItems:CurriculumItem[]; teachIndex:number; teachStudying:boolean; teachInput:string; teachAttempts:number; teachFeedback:"correct"|"wrong"|null; teachHook:boolean; teachReveal:boolean;
  reviewQueue:VocabularyWord[]; reviewIndex:number; reviewInput:string; reviewAttempts:number; reviewFeedback:"correct"|"wrong"|null; reviewHook:boolean; reviewReveal:boolean;
  quizQuestions:QuizQuestion[]; quizAnswers:Record<string,string>; quizGrade:QuizGrade|null; sessionLearned:LearnedChunk[];
  shownTranslations:Record<number,boolean>; shownHints:Record<number,boolean>; shownAnswers:Record<number,boolean>;
};

const PROGRESS_KEY="dutch-tutor-progress-v4";
const ACTIVE_KEY="dutch-tutor-active-v4";
const day=(offset=0)=>{const d=new Date();d.setDate(d.getDate()+offset);return d.toISOString().slice(0,10)};
const normalize=(s:string)=>s.trim().toLocaleLowerCase("nl-NL").replace(/[.!?,'’]/g,"").replace(/\s+/g," ");
const uid=()=>Math.random().toString(36).slice(2,10);
const clean=(s:string)=>s.replace(/\*\*/g,"");

const CORE:CurriculumItem[]=[
{id:"hallo",dutch:"hallo",english:"hello",pronunciation:"HAH-loh",memoryHook:"Hallo and hello are almost twins — just swap the first vowel.",exampleDutch:"Hallo! Hoe gaat het?",exampleEnglish:"Hello! How are you?",topic:"survival"},
{id:"ja",dutch:"ja",english:"yes",pronunciation:"yah",memoryHook:"Think 'ya!' = yes.",exampleDutch:"Ja, ik heb les.",exampleEnglish:"Yes, I have class.",topic:"survival"},
{id:"nee",dutch:"nee",english:"no",pronunciation:"nay",memoryHook:"A horse says 'neigh' — hear 'nay' and think NO → nee.",exampleDutch:"Nee, niet vandaag.",exampleEnglish:"No, not today.",topic:"survival"},
{id:"dank-je",dutch:"dank je",english:"thank you",pronunciation:"dahnk yuh",memoryHook:"Dank je sounds a little like 'thank ya.'",exampleDutch:"Goed, dank je.",exampleEnglish:"Good, thank you.",topic:"survival"},
{id:"ik-ben",dutch:"ik ben",english:"I am",pronunciation:"ik ben",memoryHook:"Picture a guy named Ben saying: 'Ik BEN = I AM Ben.'",exampleDutch:"Ik ben student.",exampleEnglish:"I am a student.",topic:"core"},
{id:"ik-heb",dutch:"ik heb",english:"I have",pronunciation:"ik hep",memoryHook:"HEB = HAVE: 'I HEB it' → I have it.",exampleDutch:"Ik heb vandaag les.",exampleEnglish:"I have class today.",topic:"core"},
{id:"ik-ga",dutch:"ik ga",english:"I go / I am going",pronunciation:"ik kha",memoryHook:"GA = GO — same G, same movement.",exampleDutch:"Ik ga naar de les.",exampleEnglish:"I am going to class.",topic:"core"},
{id:"ik-doe",dutch:"ik doe",english:"I do",pronunciation:"ik doo",memoryHook:"DOE looks and sounds like DO.",exampleDutch:"Ik doe mijn huiswerk.",exampleEnglish:"I do my homework.",topic:"core"},
{id:"ik-wil",dutch:"ik wil",english:"I want",pronunciation:"ik vil",memoryHook:"If you WILL something, you WANT it → wil.",exampleDutch:"Ik wil Nederlands leren.",exampleEnglish:"I want to learn Dutch.",topic:"core"},
{id:"ik-kan",dutch:"ik kan",english:"I can",pronunciation:"ik kan",memoryHook:"KAN = CAN. Nearly identical.",exampleDutch:"Ik kan een beetje Nederlands spreken.",exampleEnglish:"I can speak a little Dutch.",topic:"core"},
{id:"ik-moet",dutch:"ik moet",english:"I have to / must",pronunciation:"ik moot",memoryHook:"MOET and MUST both start with M and mean obligation.",exampleDutch:"Ik moet straks trainen.",exampleEnglish:"I have to train later.",topic:"core"},
{id:"ik-weet",dutch:"ik weet",english:"I know",pronunciation:"ik vayt",memoryHook:"Use your WIT to KNOW something → weet.",exampleDutch:"Ik weet het niet.",exampleEnglish:"I don't know.",topic:"core"},
{id:"ik-denk",dutch:"ik denk",english:"I think",pronunciation:"ik denk",memoryHook:"Denk is your thinking word: 'I think' → ik denk.",exampleDutch:"Ik denk van wel.",exampleEnglish:"I think so.",topic:"opinions"},
{id:"ik-vind",dutch:"ik vind",english:"I think / I find",pronunciation:"ik fint",memoryHook:"FIND your opinion → vind = find/think.",exampleDutch:"Ik vind Nederlands leuk.",exampleEnglish:"I think Dutch is fun.",topic:"opinions"},
{id:"begrijp",dutch:"ik begrijp het niet",english:"I don't understand",pronunciation:"ik buh-KHRIPE ut neet",memoryHook:"Niet = NOT; if you don't grasp it, you begrijp het niet.",exampleDutch:"Sorry, ik begrijp het niet.",exampleEnglish:"Sorry, I don't understand.",topic:"survival"},
{id:"betekent",dutch:"wat betekent ...?",english:"what does ... mean?",pronunciation:"vat buh-TAY-kent",memoryHook:"Betekent = means; pair it with 'what does that mean?'.",exampleDutch:"Wat betekent 'straks'?",exampleEnglish:"What does 'straks' mean?",topic:"survival"},
{id:"herhalen",dutch:"kun je dat herhalen?",english:"can you repeat that?",pronunciation:"kun yuh dat hair-HAH-len",memoryHook:"Hear it again → herhalen = repeat.",exampleDutch:"Kun je dat herhalen?",exampleEnglish:"Can you repeat that?",topic:"survival"},
{id:"hoe-gaat",dutch:"hoe gaat het?",english:"how are you?",pronunciation:"hoo khaat ut",memoryHook:"Literally think 'how goes it?' → hoe gaat het?",exampleDutch:"Hoi! Hoe gaat het?",exampleEnglish:"Hi! How are you?",topic:"conversation"},
{id:"gaat-goed",dutch:"het gaat goed",english:"I'm doing well",pronunciation:"ut khaat khoot",memoryHook:"Goed = good. 'It goes good' → I'm doing well.",exampleDutch:"Het gaat goed, dank je.",exampleEnglish:"I'm doing well, thank you.",topic:"conversation"},
{id:"waar",dutch:"waar",english:"where",pronunciation:"vaar",memoryHook:"WAAR sounds like 'where' with a V.",exampleDutch:"Waar ben je?",exampleEnglish:"Where are you?",topic:"questions"},
{id:"wat",dutch:"wat",english:"what",pronunciation:"vat",memoryHook:"WAT = WHAT minus the H.",exampleDutch:"Wat doe je?",exampleEnglish:"What are you doing?",topic:"questions"},
{id:"wanneer",dutch:"wanneer",english:"when",pronunciation:"vah-NAIR",memoryHook:"WANNEER starts like WHEN.",exampleDutch:"Wanneer ga je trainen?",exampleEnglish:"When are you going to train?",topic:"questions"},
{id:"waarom",dutch:"waarom",english:"why",pronunciation:"VAH-rom",memoryHook:"Pair waarom with the answer-word omdat: WHY? → BECAUSE.",exampleDutch:"Waarom leer je Nederlands?",exampleEnglish:"Why are you learning Dutch?",topic:"questions"},
{id:"omdat",dutch:"omdat",english:"because",pronunciation:"om-DAT",memoryHook:"WHY? waarom. BECAUSE? omdat. Learn them as a pair.",exampleDutch:"Ik leer Nederlands omdat ik het leuk vind.",exampleEnglish:"I learn Dutch because I like it.",topic:"connectors"},
{id:"en",dutch:"en",english:"and",pronunciation:"en",memoryHook:"EN sounds like the start of AND.",exampleDutch:"Ik studeer en ik train.",exampleEnglish:"I study and I train.",topic:"connectors"},
{id:"maar",dutch:"maar",english:"but",pronunciation:"mahr",memoryHook:"Imagine: 'I want MORE, BUT...' → maar.",exampleDutch:"Ik ben moe, maar het gaat goed.",exampleEnglish:"I am tired, but I'm doing well.",topic:"connectors"},
{id:"ook",dutch:"ook",english:"also",pronunciation:"ohk",memoryHook:"OOK adds one more thing: 'also'.",exampleDutch:"Ik leer ook Nederlands.",exampleEnglish:"I also learn Dutch.",topic:"connectors"},
{id:"nu",dutch:"nu",english:"now",pronunciation:"new",memoryHook:"NU = NOW, both start N and are tiny time words.",exampleDutch:"Ik ben nu thuis.",exampleEnglish:"I am home now.",topic:"time"},
{id:"straks",dutch:"straks",english:"later / in a little while",pronunciation:"strahks",memoryHook:"Think 'straight after this' → straks = a little later.",exampleDutch:"Ik ga straks trainen.",exampleEnglish:"I am going to practice later.",topic:"time"},
{id:"morgen",dutch:"morgen",english:"tomorrow",pronunciation:"MOR-khen",memoryHook:"Tomorrow comes in the MORNING → morgen.",exampleDutch:"Morgen heb ik les.",exampleEnglish:"Tomorrow I have class.",topic:"time"},
{id:"gisteren",dutch:"gisteren",english:"yesterday",pronunciation:"KHIS-ter-en",memoryHook:"Gisteren = yesterday: think HISTORY happened yesterday.",exampleDutch:"Gisteren had ik training.",exampleEnglish:"Yesterday I had practice.",topic:"time"},
{id:"les",dutch:"de les",english:"class / lesson",pronunciation:"duh les",memoryHook:"LES = LESson.",exampleDutch:"Ik ga naar de les.",exampleEnglish:"I am going to class.",topic:"college"},
{id:"huiswerk",dutch:"huiswerk",english:"homework",pronunciation:"HOWS-vairk",memoryHook:"Huis = house + werk = work → house-work = homework.",exampleDutch:"Ik doe mijn huiswerk.",exampleEnglish:"I do my homework.",topic:"college"},
{id:"training",dutch:"training",english:"practice / training",pronunciation:"TRAY-ning",memoryHook:"Freebie: training means training/practice.",exampleDutch:"Ik heb vanmiddag training.",exampleEnglish:"I have practice this afternoon.",topic:"track"},
{id:"trainen",dutch:"trainen",english:"to train / practice",pronunciation:"TRAY-nen",memoryHook:"Train → trainen. Same root.",exampleDutch:"Ik ga straks trainen.",exampleEnglish:"I am going to practice later.",topic:"track"},
{id:"eten",dutch:"eten",english:"to eat",pronunciation:"AY-ten",memoryHook:"ETEN starts with E like EAT.",exampleDutch:"Ik ga nu eten.",exampleEnglish:"I am going to eat now.",topic:"daily"},
{id:"drinken",dutch:"drinken",english:"to drink",pronunciation:"DRING-ken",memoryHook:"DRINK is sitting right inside drinken.",exampleDutch:"Ik drink water.",exampleEnglish:"I drink water.",topic:"daily"},
{id:"slapen",dutch:"slapen",english:"to sleep",pronunciation:"SLAH-pen",memoryHook:"SLAP the pillow and go to sleep → slapen.",exampleDutch:"Ik wil slapen.",exampleEnglish:"I want to sleep.",topic:"daily"},
{id:"leuk",dutch:"leuk",english:"fun / nice",pronunciation:"lurk",memoryHook:"Think 'look, that's nice!' → leuk.",exampleDutch:"Dat is leuk.",exampleEnglish:"That is fun.",topic:"descriptions"},
{id:"goed",dutch:"goed",english:"good / well",pronunciation:"khoot",memoryHook:"GOED = GOOD with Dutch pronunciation.",exampleDutch:"Dat klinkt goed.",exampleEnglish:"That sounds good.",topic:"descriptions"},
{id:"blij",dutch:"blij",english:"happy",pronunciation:"bligh",memoryHook:"BLij → picture a BLISSFUL smile.",exampleDutch:"Ik ben blij.",exampleEnglish:"I am happy.",topic:"feelings"},
{id:"druk",dutch:"druk",english:"busy",pronunciation:"druk",memoryHook:"A busy day puts you under pressure — druk also means pressure/print.",exampleDutch:"Ik ben vandaag druk.",exampleEnglish:"I am busy today.",topic:"feelings"},
{id:"honger",dutch:"ik heb honger",english:"I am hungry",pronunciation:"ik hep HONG-er",memoryHook:"HONGER looks like HUNGER.",exampleDutch:"Ik heb honger na de training.",exampleEnglish:"I am hungry after practice.",topic:"daily"}
];

const OPENERS=[
{text:"Hoi! Hoe gaat het vandaag?",translation:"Hi! How are you today?",hint:"Try: Het gaat ..."},
{text:"Waar ben je nu?",translation:"Where are you now?",hint:"Try: Ik ben ..."},
{text:"Wat ga je straks doen?",translation:"What are you going to do later?",hint:"Try: Ik ga ..."},
{text:"Heb je vandaag les?",translation:"Do you have class today?",hint:"Try: Ja, ik heb ... / Nee, ..."},
{text:"Wat wil je vanavond doen?",translation:"What do you want to do tonight?",hint:"Try: Ik wil ..."},
{text:"Wanneer ga je trainen?",translation:"When are you going to train?",hint:"Try: Ik ga ... trainen."},
{text:"Wat vind je leuk?",translation:"What do you like?",hint:"Try: Ik vind ... leuk."},
{text:"Ben je vandaag druk?",translation:"Are you busy today?",hint:"Try: Ja, ik ben ... / Nee, ..."}
];
const starterFor=(n:number):ChatMessage[]=>[{role:"assistant",...OPENERS[n%OPENERS.length]}];

const STARTER_WORDS:VocabularyWord[]=[
{id:"denken",dutch:"denken",english:"to think",pronunciation:"DEN-ken",memoryHook:"Denk is your thinking word.",mastery:42,correctRecall:3,wrongRecall:4,correctUse:1,wrongUse:2,nextReview:day(0)},
{id:"geven",dutch:"geven",english:"to give",pronunciation:"GHAY-ven",memoryHook:"GEVEN = GIVE — both start G-V.",mastery:40,correctRecall:2,wrongRecall:4,correctUse:1,wrongUse:2,nextReview:day(0)},
{id:"geld",dutch:"geld",english:"money",pronunciation:"khelt",memoryHook:"GELD sounds like gold — gold = money.",mastery:38,correctRecall:2,wrongRecall:5,correctUse:0,wrongUse:2,nextReview:day(0)},
{id:"telefoon",dutch:"telefoon",english:"phone",pronunciation:"tay-luh-FOHN",memoryHook:"TELEFOON looks like telephone.",mastery:54,correctRecall:4,wrongRecall:3,correctUse:1,wrongUse:1,nextReview:day(0)}
];

const FALLBACK_QUIZ:QuizQuestion[]=[
{id:"v1",part:1,prompt:"yes",word:"ja"},{id:"v2",part:1,prompt:"no",word:"nee"},{id:"v3",part:1,prompt:"I want",word:"ik wil"},
{id:"d1",part:2,prompt:"I have class today."},{id:"d2",part:2,prompt:"I am going to practice later."},
{id:"e1",part:3,prompt:"Ik wil Nederlands leren."},{id:"e2",part:3,prompt:"Ik ben vandaag druk."},
{id:"b1",part:4,prompt:"Build: I am going to class now.",tokens:["ik","ga","nu","naar","de","les","ben","goed"]},
{id:"c1",part:5,prompt:"Wat ga je straks doen? Answer naturally in Dutch."}
];

function migrateProgress():ProgressState{
  try{
    const v4=localStorage.getItem(PROGRESS_KEY);if(v4)return JSON.parse(v4);
    const v3=localStorage.getItem("dutch-tutor-progress-v3");if(v3){const p=JSON.parse(v3);return{...p,version:4,vocabulary:(p.vocabulary||[]).map((w:VocabularyWord)=>({...w,memoryHook:w.memoryHook||CORE.find(x=>normalize(x.dutch)===normalize(w.dutch))?.memoryHook||""}))};}
  }catch{}
  return{version:4,wordsLearned:STARTER_WORDS.length,lastQuiz:0,sessions:0,vocabulary:STARTER_WORDS,recentScores:[],commonMistakes:[]};
}

export default function DutchTutorV4(){
  const [tab,setTab]=useState<Tab>("home"),[minutes,setMinutes]=useState(10),[stage,setStage]=useState<Stage>("teach");
  const [progress,setProgress]=useState<ProgressState>({version:4,wordsLearned:0,lastQuiz:0,sessions:0,vocabulary:STARTER_WORDS,recentScores:[],commonMistakes:[]});
  const [loaded,setLoaded]=useState(false),[activeMode,setActiveMode]=useState<ActiveMode|null>(null);
  const [lessonItems,setLessonItems]=useState<CurriculumItem[]>([]),[teachIndex,setTeachIndex]=useState(0),[teachStudying,setTeachStudying]=useState(true),[teachInput,setTeachInput]=useState(""),[teachAttempts,setTeachAttempts]=useState(0),[teachFeedback,setTeachFeedback]=useState<"correct"|"wrong"|null>(null),[teachHook,setTeachHook]=useState(false),[teachReveal,setTeachReveal]=useState(false);
  const [reviewQueue,setReviewQueue]=useState<VocabularyWord[]>([]),[reviewIndex,setReviewIndex]=useState(0),[reviewInput,setReviewInput]=useState(""),[reviewAttempts,setReviewAttempts]=useState(0),[reviewFeedback,setReviewFeedback]=useState<"correct"|"wrong"|null>(null),[reviewHook,setReviewHook]=useState(false),[reviewReveal,setReviewReveal]=useState(false);
  const [messages,setMessages]=useState<ChatMessage[]>(starterFor(0)),[input,setInput]=useState(""),[turns,setTurns]=useState(0),[pendingRetry,setPendingRetry]=useState<Correction|null>(null),[loading,setLoading]=useState(false),[apiError,setApiError]=useState("");
  const [shownTranslations,setShownTranslations]=useState<Record<number,boolean>>({}),[shownHints,setShownHints]=useState<Record<number,boolean>>({}),[shownAnswers,setShownAnswers]=useState<Record<number,boolean>>({});
  const [quizQuestions,setQuizQuestions]=useState<QuizQuestion[]>(FALLBACK_QUIZ),[quizAnswers,setQuizAnswers]=useState<Record<string,string>>({}),[quizGrade,setQuizGrade]=useState<QuizGrade|null>(null),[quizLoading,setQuizLoading]=useState(false),[grading,setGrading]=useState(false),[sessionLearned,setSessionLearned]=useState<LearnedChunk[]>([]);
  const inputRef=useRef<HTMLInputElement>(null);

  useEffect(()=>{setProgress(migrateProgress());try{const raw=localStorage.getItem(ACTIVE_KEY);if(raw){const s=JSON.parse(raw) as SavedSession;if(Date.now()-s.savedAt<7*86400000){setActiveMode(s.activeMode);setMinutes(s.minutes);setStage(s.stage);setMessages(s.messages||starterFor(0));setTurns(s.turns||0);setPendingRetry(s.pendingRetry||null);setLessonItems(s.lessonItems||[]);setTeachIndex(s.teachIndex||0);setTeachStudying(s.teachStudying!==false);setTeachInput(s.teachInput||"");setTeachAttempts(s.teachAttempts||0);setTeachFeedback(s.teachFeedback||null);setTeachHook(Boolean(s.teachHook));setTeachReveal(Boolean(s.teachReveal));setReviewQueue(s.reviewQueue||[]);setReviewIndex(s.reviewIndex||0);setReviewInput(s.reviewInput||"");setReviewAttempts(s.reviewAttempts||0);setReviewFeedback(s.reviewFeedback||null);setReviewHook(Boolean(s.reviewHook));setReviewReveal(Boolean(s.reviewReveal));setQuizQuestions(s.quizQuestions?.length?s.quizQuestions:FALLBACK_QUIZ);setQuizAnswers(s.quizAnswers||{});setQuizGrade(s.quizGrade||null);setSessionLearned(s.sessionLearned||[]);setShownTranslations(s.shownTranslations||{});setShownHints(s.shownHints||{});setShownAnswers(s.shownAnswers||{});setTab(s.activeMode);}}}catch{}setLoaded(true)},[]);
  useEffect(()=>{if(loaded)try{localStorage.setItem(PROGRESS_KEY,JSON.stringify(progress))}catch{}},[progress,loaded]);
  useEffect(()=>{if(!loaded)return;if(!activeMode){try{localStorage.removeItem(ACTIVE_KEY)}catch{};return}const s:SavedSession={savedAt:Date.now(),activeMode,minutes,stage,messages,turns,pendingRetry,lessonItems,teachIndex,teachStudying,teachInput,teachAttempts,teachFeedback,teachHook,teachReveal,reviewQueue,reviewIndex,reviewInput,reviewAttempts,reviewFeedback,reviewHook,reviewReveal,quizQuestions,quizAnswers,quizGrade,sessionLearned,shownTranslations,shownHints,shownAnswers};try{localStorage.setItem(ACTIVE_KEY,JSON.stringify(s))}catch{}},[loaded,activeMode,minutes,stage,messages,turns,pendingRetry,lessonItems,teachIndex,teachStudying,teachInput,teachAttempts,teachFeedback,teachHook,teachReveal,reviewQueue,reviewIndex,reviewInput,reviewAttempts,reviewFeedback,reviewHook,reviewReveal,quizQuestions,quizAnswers,quizGrade,sessionLearned,shownTranslations,shownHints,shownAnswers]);

  const dueWords=useMemo(()=>progress.vocabulary.filter(w=>w.nextReview<=day()).sort((a,b)=>a.mastery-b.mastery),[progress.vocabulary]);
  const avgScore=useMemo(()=>progress.recentScores.length?Math.round(progress.recentScores.reduce((a,b)=>a+b,0)/progress.recentScores.length):0,[progress.recentScores]);
  const level=avgScore>=90&&progress.sessions>=24?4:avgScore>=84&&progress.sessions>=16?3:avgScore>=76&&progress.sessions>=10?2:1;
  const targetTurns=minutes===5?1:minutes===10?2:4;
  const currentLesson=lessonItems[teachIndex],currentReview=reviewQueue[reviewIndex];

  const patchWord=(dutch:string,patch:Partial<VocabularyWord>)=>setProgress(p=>({...p,vocabulary:p.vocabulary.map(w=>normalize(w.dutch)===normalize(dutch)?{...w,...patch}:w)}));
  function addCurriculum(items:CurriculumItem[]){setProgress(p=>{const v=[...p.vocabulary];let added=0;for(const x of items){if(v.some(w=>normalize(w.dutch)===normalize(x.dutch)))continue;v.push({id:x.id,dutch:x.dutch,english:x.english,pronunciation:x.pronunciation,memoryHook:x.memoryHook,mastery:15,correctRecall:0,wrongRecall:0,correctUse:0,wrongUse:0,nextReview:day(1),lastSeen:day()});added++}return{...p,vocabulary:v,wordsLearned:p.wordsLearned+added}})}
  function addLearned(items:LearnedChunk[]){if(!items?.length)return;setSessionLearned(p=>{const m=[...p];for(const x of items)if(x?.dutch&&!m.some(y=>normalize(y.dutch)===normalize(x.dutch)))m.push(x);return m.slice(-20)});setProgress(p=>{const v=[...p.vocabulary];let added=0;for(const x of items){if(!x?.dutch||v.some(w=>normalize(w.dutch)===normalize(x.dutch)))continue;v.push({id:uid(),dutch:x.dutch,english:x.english||"",pronunciation:x.pronunciation||"",memoryHook:x.memoryHook||"",mastery:20,correctRecall:0,wrongRecall:0,correctUse:0,wrongUse:0,nextReview:day(1),lastSeen:day()});added++}return{...p,vocabulary:v,wordsLearned:p.wordsLearned+added}})}

  function startSession(m:number){
    if(activeMode&&!window.confirm("Start a new session? Your current session will be replaced."))return;
    const known=new Set(progress.vocabulary.map(w=>normalize(w.dutch)));const unseen=CORE.filter(x=>!known.has(normalize(x.dutch)));
    let newCount=m===5?2:m===10?4:6;if(avgScore&&avgScore<55)newCount=Math.max(2,newCount-1);if(level>=2)newCount=Math.max(1,newCount-1);
    const fresh=unseen.slice(0,newCount),freshSet=new Set(fresh.map(x=>normalize(x.dutch))),reviewCount=m===5?2:m===10?3:5;
    const queue=dueWords.filter(w=>!freshSet.has(normalize(w.dutch))).slice(0,reviewCount);addCurriculum(fresh);
    setMinutes(m);setLessonItems(fresh);setTeachIndex(0);setTeachStudying(true);setTeachInput("");setTeachAttempts(0);setTeachFeedback(null);setTeachHook(false);setTeachReveal(false);
    setReviewQueue(queue);setReviewIndex(0);setReviewInput("");setReviewAttempts(0);setReviewFeedback(null);setReviewHook(false);setReviewReveal(false);
    setMessages(starterFor(progress.sessions+1));setTurns(0);setPendingRetry(null);setShownTranslations({});setShownHints({});setShownAnswers({});setQuizQuestions(FALLBACK_QUIZ);setQuizAnswers({});setQuizGrade(null);setSessionLearned(fresh);
    setStage(fresh.length?"teach":queue.length?"review":"conversation");setActiveMode("learn");setTab("learn");setApiError("");
  }

  function submitTeach(e:FormEvent){e.preventDefault();if(!currentLesson||teachFeedback==="correct")return;const ok=normalize(teachInput)===normalize(currentLesson.dutch);const n=teachAttempts+1;setTeachAttempts(n);setTeachFeedback(ok?"correct":"wrong");const w=progress.vocabulary.find(x=>normalize(x.dutch)===normalize(currentLesson.dutch));if(w)patchWord(w.dutch,{mastery:Math.max(5,Math.min(100,w.mastery+(ok?(teachReveal?2:8):-4))),correctRecall:w.correctRecall+(ok?1:0),wrongRecall:w.wrongRecall+(ok?0:1),lastSeen:day(),nextReview:day(ok?(teachReveal?1:2):1)});if(!ok){setTeachInput("");if(n>=2)setTeachHook(true)}}
  function nextTeach(){if(teachIndex+1<lessonItems.length){setTeachIndex(i=>i+1);setTeachStudying(true);setTeachInput("");setTeachAttempts(0);setTeachFeedback(null);setTeachHook(false);setTeachReveal(false)}else{setStage(reviewQueue.length?"review":"conversation")}}
  function submitReview(e:FormEvent){e.preventDefault();if(!currentReview||reviewFeedback==="correct")return;const ok=normalize(reviewInput)===normalize(currentReview.dutch);const n=reviewAttempts+1;setReviewAttempts(n);setReviewFeedback(ok?"correct":"wrong");patchWord(currentReview.dutch,{mastery:Math.max(5,Math.min(100,currentReview.mastery+(ok?(reviewReveal?1:6):-7))),correctRecall:currentReview.correctRecall+(ok?1:0),wrongRecall:currentReview.wrongRecall+(ok?0:1),lastSeen:day(),nextReview:day(ok?(reviewReveal?1:(currentReview.mastery>=75?7:3)):1)});if(!ok){setReviewInput("");if(n>=2)setReviewHook(true)}}
  function nextReview(){if(reviewIndex+1<reviewQueue.length){setReviewIndex(i=>i+1);setReviewInput("");setReviewAttempts(0);setReviewFeedback(null);setReviewHook(false);setReviewReveal(false)}else{setStage("conversation");setTimeout(()=>inputRef.current?.focus(),50)}}

  function speak(text:string){if(typeof window==="undefined"||!("speechSynthesis"in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(clean(text));u.lang="nl-NL";u.rate=.88;window.speechSynthesis.speak(u)}
  function startVoice(){const w=window as any,R=w.SpeechRecognition||w.webkitSpeechRecognition;if(!R){setApiError("Voice input is not supported here. You can still type.");return}const r=new R();r.lang="nl-NL";r.interimResults=false;r.onresult=(e:any)=>setInput(e.results?.[0]?.[0]?.transcript||"");r.onerror=()=>setApiError("I couldn't hear that clearly. Try again or type it.");r.start()}

  async function sendMessage(e:FormEvent){e.preventDefault();const text=input.trim();if(!text||loading)return;setInput("");const next=[...messages,{role:"user" as const,text}];setMessages(next);setLoading(true);setApiError("");try{const res=await fetch("/api/tutor",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text,history:next.slice(-14),minutes,immersionLevel:level,knownWords:progress.vocabulary.filter(w=>w.mastery>=55).map(w=>w.dutch).slice(0,120),weakWords:dueWords.map(w=>w.dutch).slice(0,15),focusWords:lessonItems.map(x=>x.dutch),commonMistakes:progress.commonMistakes.slice(0,10),pendingRetry})});const data=await res.json();if(!res.ok)throw new Error(data?.error||"Tutor request failed");const correction=data.correction?.better?data.correction as Correction:undefined;setMessages(p=>[...p,{role:"assistant",text:clean(data.reply||"Goed!"),translation:data.translation,hint:data.hint,correction,retryRequired:Boolean(data.retryRequired)}]);setTurns(t=>t+1);setPendingRetry(data.retryRequired&&correction?correction:null);addLearned(data.learnedChunks||[]);if(correction)setProgress(p=>({...p,commonMistakes:[{wrong:correction.wrong,correct:correction.better,why:correction.why},...p.commonMistakes.filter(m=>m.wrong!==correction.wrong)].slice(0,15)}))}catch(err){setApiError(err instanceof Error?err.message:"Could not reach tutor.")}finally{setLoading(false)}}

  async function beginQuiz(){setActiveMode("quiz");setTab("quiz");setQuizLoading(true);setQuizAnswers({});setQuizGrade(null);setApiError("");try{const res=await fetch("/api/quiz/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({level,minutes,transcript:messages.slice(-16),weakWords:[...progress.vocabulary].sort((a,b)=>a.mastery-b.mastery).slice(0,10).map(w=>({dutch:w.dutch,english:w.english})),learnedChunks:sessionLearned,focusWords:lessonItems.map(x=>({dutch:x.dutch,english:x.english})),commonMistakes:progress.commonMistakes.slice(0,8)})});const data=await res.json();if(!res.ok||!Array.isArray(data.questions)||data.questions.length<5)throw new Error(data?.error||"Could not build quiz");setQuizQuestions(data.questions)}catch{setQuizQuestions(FALLBACK_QUIZ);setApiError("Using the built-in quick quiz this time.")}finally{setQuizLoading(false)}}
  async function gradeQuiz(e:FormEvent){e.preventDefault();setGrading(true);try{const res=await fetch("/api/quiz",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({questions:quizQuestions,answers:quizAnswers,level})});const data=await res.json();if(!res.ok)throw new Error(data?.error||"Could not grade");setQuizGrade(data);setProgress(p=>({...p,lastQuiz:data.score,sessions:p.sessions+1,recentScores:[...p.recentScores,data.score].slice(-8)}))}catch(err){setApiError(err instanceof Error?err.message:"Quiz grading failed.")}finally{setGrading(false)}}
  function finishSession(){setActiveMode(null);setSessionLearned([]);setTab("home")}
  const partTitle=(n:number)=>["","Vocabulary recall","English → Dutch","Dutch → English","Build the sentence","Conversation"][n];

  return <main className="shell">
    <header className="header"><div><div className="brand">Dutch Tutor 🇳🇱</div><div className="subtle">Memory hooks · active recall · real conversation</div></div><span className="badge">Level {level}</span></header>

    {tab==="home"&&<div className="stack">
      <section className="hero card"><div className="kicker">RECOMMENDED DAILY</div><h1>10 focused minutes.</h1><p className="subtle">Learn a few useful chunks with memory hooks, recall them without seeing the answer, review older words, then use them in conversation.</p><div className="grid3">{[5,10,20].map(m=><button className="timeButton" key={m} onClick={()=>startSession(m)}><strong>{m}</strong><span>min</span></button>)}</div></section>
      {activeMode&&<section className="card"><div className="kicker">IN PROGRESS</div><strong>Your {activeMode==="quiz"?"quiz":"lesson"} is saved.</strong><button className="primary compact" onClick={()=>setTab(activeMode)}>Resume</button></section>}
      <section className="stats"><div className="stat"><strong>{dueWords.length}</strong><span>due today</span></div><div className="stat"><strong>{progress.vocabulary.length}</strong><span>tracked chunks</span></div><div className="stat"><strong>{progress.lastQuiz||"—"}{progress.lastQuiz?"%":""}</strong><span>last quiz</span></div><div className="stat"><strong>{progress.sessions}</strong><span>sessions</span></div></section>
      <section className="card"><div className="sectionTitle noTop">Why the memory hooks?</div><p className="subtle">A quick sound/image connection gives your brain a path to the Dutch word. Then the app immediately makes you retrieve it, so the hook becomes a bridge — not a crutch.</p></section>
    </div>}

    {tab==="learn"&&<div className="stack">
      <section className="card sessionHeader"><div><div className="kicker">{minutes}-MINUTE SESSION</div><strong>{stage==="teach"?`Learn · ${teachIndex+1}/${lessonItems.length}`:stage==="review"?`Review · ${reviewIndex+1}/${reviewQueue.length}`:`Conversation · ${Math.min(turns,targetTurns)}/${targetTurns}`}</strong></div><button className="textButton" onClick={beginQuiz}>Finish & quiz</button></section>

      {stage==="teach"&&currentLesson&&<section className="card recallCard"><div className="kicker">NEW HIGH-FREQUENCY CHUNK</div>{teachStudying?<><h2>{currentLesson.dutch}</h2><div style={{fontSize:18,fontWeight:750}}>{currentLesson.english}</div><p className="subtle">Pronunciation: {currentLesson.pronunciation}</p><div className="helper"><strong>🧠 Memory hook:</strong> {currentLesson.memoryHook}</div><div className="success"><strong>{currentLesson.exampleDutch}</strong><br/>{currentLesson.exampleEnglish}</div><div style={{display:"flex",gap:8,marginTop:12}}><button className="secondary" onClick={()=>speak(currentLesson.dutch)}>🔊 Listen</button><button className="primary compact" style={{marginTop:0}} onClick={()=>{setTeachStudying(false);setTeachInput("");setTeachAttempts(0);setTeachFeedback(null);setTeachHook(false);setTeachReveal(false)}}>Test me</button></div></>:<form onSubmit={submitTeach}><p className="subtle">Type the Dutch from memory. The answer stays hidden.</p><h2>{currentLesson.english}</h2><input className="bigInput" value={teachInput} onChange={e=>setTeachInput(e.target.value)} autoFocus placeholder="Dutch answer..."/>{teachFeedback==="wrong"&&<div className="error" style={{marginTop:12}}><strong>Not yet.</strong> Try once more from memory. {teachAttempts>=2?"Use the hook or reveal only if you truly need it.":"The answer is still hidden."}</div>}{teachHook&&<div className="helper"><strong>🧠 Memory hook:</strong> {currentLesson.memoryHook}</div>}{teachReveal&&<div className="success"><strong>{currentLesson.dutch}</strong> · {currentLesson.pronunciation}<br/><span className="subtle">Say it aloud, then type it once from memory.</span></div>}{teachFeedback==="correct"&&<div className="success">✓ Correct. Say it aloud once.</div>}{teachFeedback==="correct"?<button type="button" className="primary" onClick={nextTeach}>Next</button>:<><button className="primary">Check</button><div style={{display:"flex",gap:8,marginTop:8}}><button type="button" className="secondary" onClick={()=>setTeachHook(true)}>🧠 Memory hook</button>{teachAttempts>=2&&<button type="button" className="secondary" onClick={()=>setTeachReveal(true)}>Reveal answer</button>}</div></>}</form>}</section>}

      {stage==="review"&&currentReview&&<section className="card recallCard"><div className="kicker">SPACED RETRIEVAL</div><p className="subtle">English → Dutch. No answer is shown automatically.</p><h2>{currentReview.english}</h2><form onSubmit={submitReview}><input className="bigInput" value={reviewInput} onChange={e=>setReviewInput(e.target.value)} autoFocus placeholder="Dutch..."/>{reviewFeedback==="wrong"&&<div className="error" style={{marginTop:12}}>Not yet — try again. The answer is hidden.</div>}{reviewHook&&currentReview.memoryHook&&<div className="helper"><strong>🧠 Memory hook:</strong> {currentReview.memoryHook}</div>}{reviewReveal&&<div className="success"><strong>{currentReview.dutch}</strong> · {currentReview.pronunciation}</div>}{reviewFeedback==="correct"&&<div className="success">✓ Correct</div>}{reviewFeedback==="correct"?<button type="button" className="primary" onClick={nextReview}>Next</button>:<><button className="primary">Check</button><div style={{display:"flex",gap:8,marginTop:8}}>{currentReview.memoryHook&&<button type="button" className="secondary" onClick={()=>setReviewHook(true)}>🧠 Memory hook</button>}{reviewAttempts>=2&&<button type="button" className="secondary" onClick={()=>setReviewReveal(true)}>Reveal answer</button>}</div></>}</form></section>}

      {stage==="conversation"&&<><div className="coachStrip"><span>🇳🇱 Try Dutch first</span><span>🇺🇸 English if stuck</span><span>🧠 Use today's chunks</span></div><div className="chat">{messages.map((m,i)=><div key={i}><div className={`bubble ${m.role==="assistant"?"tutor":"user"}`}>{m.text}</div>{m.role==="assistant"&&<><div className="messageTools"><button onClick={()=>speak(m.text)}>🔊 Listen</button><button onClick={()=>setShownTranslations(x=>({...x,[i]:!x[i]}))}>🇺🇸 Translate</button><button onClick={()=>setShownHints(x=>({...x,[i]:!x[i]}))}>💡 Hint</button></div>{shownTranslations[i]&&m.translation&&<div className="helper">{m.translation}</div>}{shownHints[i]&&m.hint&&<div className="helper">{m.hint}</div>}{m.correction&&<div className="correction"><div className="kicker">CORRECTION</div><div className="strike">{m.correction.wrong}</div><p><strong>Hint:</strong> {m.correction.clue||m.hint}</p>{shownAnswers[i]?<><div className="better">{m.correction.better}</div><div className="subtle">{m.correction.why}</div></>:<button className="secondary" onClick={()=>setShownAnswers(x=>({...x,[i]:true}))}>Show corrected sentence</button>}<div className="retryFlag">↻ Try it again in Dutch.</div></div>}</>}</div>)}</div>{apiError&&<div className="error">{apiError}</div>}<form className="composer" onSubmit={sendMessage}><input ref={inputRef} value={input} onChange={e=>setInput(e.target.value)} placeholder="Dutch first — English if stuck..."/><button type="button" className="secondary mic" onClick={startVoice}>🎙️</button><button className="iconButton" disabled={loading}>{loading?"…":"↑"}</button></form>{turns>=targetTurns&&<button className="primary" onClick={beginQuiz}>Conversation complete — take quick quiz</button>}</>}
    </div>}

    {tab==="review"&&<div className="stack"><section className="card"><div className="sectionTitle noTop">Your vocabulary</div><p className="subtle">Weak words come back sooner. Memory hooks are rescue cues, but recall comes first.</p></section><div className="list">{[...progress.vocabulary].sort((a,b)=>a.mastery-b.mastery).slice(0,30).map(w=><div className="wordRow" key={w.id}><div><div className="word">{w.dutch}</div><div>{w.english}</div>{w.memoryHook&&<div className="subtle">🧠 {w.memoryHook}</div>}<div className="progressBar"><span style={{width:`${w.mastery}%`}}/></div><div className="subtle">{w.mastery}% mastery · next {w.nextReview}</div></div><button className="secondary" onClick={()=>speak(w.dutch)}>🔊</button></div>)}</div></div>}

    {tab==="quiz"&&<div className="stack"><section className="card"><div className="kicker">QUICK RETRIEVAL QUIZ</div><strong>{quizLoading?"Building your quiz…":"No notes. Produce what you know."}</strong></section>{apiError&&<div className="error">{apiError}</div>}{!quizLoading&&<form onSubmit={gradeQuiz}>{[1,2,3,4,5].map(part=><section className="card" key={part} style={{marginBottom:14}}><div className="sectionTitle noTop">{partTitle(part)}</div>{quizQuestions.filter(q=>q.part===part).map(q=><div className="quizItem" key={q.id}><strong>{q.prompt}</strong>{q.tokens&&<div className="tokens">{q.tokens.map((t,i)=><span key={i}>{t}</span>)}</div>}<input value={quizAnswers[q.id]||""} onChange={e=>setQuizAnswers(a=>({...a,[q.id]:e.target.value}))} placeholder="Your answer..."/>{quizGrade&&(()=>{const g=quizGrade.items.find(x=>x.id===q.id);return g?<div className={`gradeLine ${g.correct?"good":"bad"}`}>{g.correct?"✓ Correct":`✗ ${g.correction||"Incorrect"}`}<small>{g.explanation}</small></div>:null})()}</div>)}</section>)}{!quizGrade?<button className="primary" disabled={grading}>{grading?"Grading…":"Grade quiz"}</button>:<><section className="card scoreCard"><div className="score">{quizGrade.score}%</div><p className="subtle">{quizGrade.coachNote}</p></section><button type="button" className="primary" onClick={finishSession}>Finish session</button></>}</form>}</div>}

    {tab==="progress"&&<div className="stack"><section className="stats"><div className="stat"><strong>{progress.vocabulary.length}</strong><span>tracked chunks</span></div><div className="stat"><strong>{progress.sessions}</strong><span>sessions</span></div><div className="stat"><strong>{avgScore||"—"}{avgScore?"%":""}</strong><span>quiz average</span></div><div className="stat"><strong>{level}/4</strong><span>immersion level</span></div></section><section className="card"><div className="sectionTitle noTop">Recurring corrections</div>{progress.commonMistakes.length?progress.commonMistakes.slice(0,10).map((m,i)=><div className="mistake" key={i}><div className="strike">{m.wrong}</div><div className="better">{m.correct}</div><small>{m.why}</small></div>):<p className="subtle">No recurring corrections yet.</p>}</section></div>}

    <nav className="nav"><button className={tab==="home"?"active":""} onClick={()=>setTab("home")}>⌂<br/>Home</button><button className={tab==="learn"?"active":""} onClick={()=>activeMode?setTab(activeMode):startSession(10)}>◉<br/>{activeMode?"Resume":"Learn"}</button><button className={tab==="review"?"active":""} onClick={()=>setTab("review")}>↻<br/>Review</button><button className={tab==="progress"?"active":""} onClick={()=>setTab("progress")}>▥<br/>Progress</button></nav>
  </main>
}
