"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Tab="today"|"course"|"recall"|"speak"|"immerse"|"progress";
type Level="A0"|"A1"|"A2"|"B1"|"B2";
type Material={id:string;kind:"vocab"|"phrase"|"grammar"|"structure";dutch:string;english:string;notes?:string;lessonId:string;strength:number;interval:number;nextReview:string;correct:number;wrong:number};
type Lesson={id:string;title:string;url:string;date:string;level:Level;vocab:string;grammar:string;phrases:string;struggles:string;confidence:number};
type Mistake={wrong:string;correct:string;why?:string;count:number};
type Immersion={id:string;title:string;url:string;level:Level|"Natural";favorite:boolean;listened:boolean;minutes:number};
type Daily={date:string;learn:boolean;recall:boolean;speak:boolean;immersion:boolean;listeningMinutes:number;speakingMinutes:number};
type State={version:6;target:Level;lessons:Lesson[];materials:Material[];mistakes:Mistake[];immersion:Immersion[];daily:Daily;recallCorrect:number;recallWrong:number;conversationTurns:number};
type Chat={role:"assistant"|"user";text:string;translation?:string;correction?:{wrong:string;better:string;why:string}};
const KEY="dutch-course-v6";
const today=()=>new Date().toISOString().slice(0,10);
const addDays=(n:number)=>{const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const norm=(s:string)=>s.toLocaleLowerCase("nl-NL").trim().replace(/[.!?,:'’\"“”]/g,"").replace(/\s+/g," ");
const initial:State={version:6,target:"A0",lessons:[],materials:[],mistakes:[],immersion:[],daily:{date:today(),learn:false,recall:false,speak:false,immersion:false,listeningMinutes:0,speakingMinutes:0},recallCorrect:0,recallWrong:0,conversationTurns:0};
function rollDay(s:State):State{return s.daily.date===today()?s:{...s,daily:{date:today(),learn:false,recall:false,speak:false,immersion:false,listeningMinutes:0,speakingMinutes:0}}}
function parsePairs(raw:string,kind:Material["kind"],lessonId:string):Material[]{return raw.split(/\n|,/).map(x=>x.trim()).filter(Boolean).map((x,i)=>{const p=x.split(/\s*(?:=|—|->|:)\s*/);return{id:`${lessonId}-${kind}-${i}-${Date.now()}`,kind,dutch:p[0]?.trim()||x,english:p.slice(1).join(": ").trim(),lessonId,strength:0,interval:0,nextReview:today(),correct:0,wrong:0}})}
function schedule(m:Material,ok:boolean):Material{const steps=[1,3,7,14,30,60,120];const strength=ok?Math.min(6,m.strength+1):Math.max(0,m.strength-1);const interval=ok?steps[strength]:1;return{...m,strength,interval,nextReview:addDays(interval),correct:m.correct+(ok?1:0),wrong:m.wrong+(ok?0:1)}}
const seedImmersion:Immersion[]=[{id:"kim",title:"Learn Dutch with Kim / Dutchies to Be",url:"https://www.youtube.com/@learndutchwithkim",level:"A0",favorite:true,listened:false,minutes:0}];
export default function DutchCourseV6(){
 const [state,setState]=useState<State>(initial);const [tab,setTab]=useState<Tab>("today");const [quick,setQuick]=useState(false);const [loaded,setLoaded]=useState(false);
 const [lesson,setLesson]=useState({title:"",url:"",level:"A0" as Level,vocab:"",grammar:"",phrases:"",struggles:"",confidence:3});
 const [answer,setAnswer]=useState("");const [revealed,setRevealed]=useState(false);const [recallIndex,setRecallIndex]=useState(0);
 const [chat,setChat]=useState<Chat[]>([]);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [immerse,setImmerse]=useState({title:"",url:"",level:"A0" as Level|"Natural"});
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);const s=raw?JSON.parse(raw):initial;setState(rollDay({...initial,...s,immersion:s.immersion?.length?s.immersion:seedImmersion}));}catch{setState({...initial,immersion:seedImmersion})}setLoaded(true)},[]);
 useEffect(()=>{if(loaded)localStorage.setItem(KEY,JSON.stringify(state))},[state,loaded]);
 const due=useMemo(()=>state.materials.filter(x=>x.nextReview<=today()).sort((a,b)=>(b.wrong-b.correct)-(a.wrong-a.correct)),[state.materials]);const item=due[recallIndex%due.length];
 const known=state.materials.map(x=>`${x.dutch}${x.english?` = ${x.english}`:""}`).slice(-160);const weak=state.materials.filter(x=>x.wrong>x.correct||x.strength<2).map(x=>x.dutch).slice(0,30);
 const done=[state.daily.learn,state.daily.recall,state.daily.speak,state.daily.immersion].filter(Boolean).length;
 function dailyPatch(p:Partial<Daily>){setState(s=>({...s,daily:{...s.daily,...p}}))}
 function saveLesson(e:FormEvent){e.preventDefault();if(!lesson.title.trim())return;const id=`lesson-${Date.now()}`;const L:Lesson={id,title:lesson.title.trim(),url:lesson.url.trim(),date:today(),level:lesson.level,vocab:lesson.vocab,grammar:lesson.grammar,phrases:lesson.phrases,struggles:lesson.struggles,confidence:lesson.confidence};const mats=[...parsePairs(lesson.vocab,"vocab",id),...parsePairs(lesson.phrases,"phrase",id),...parsePairs(lesson.grammar,"grammar",id)];setState(s=>({...s,lessons:[...s.lessons,L],materials:[...s.materials,...mats],daily:{...s.daily,learn:true}}));setLesson({title:"",url:"",level:lesson.level,vocab:"",grammar:"",phrases:"",struggles:"",confidence:3});}
 function grade(ok:boolean){if(!item)return;setState(s=>({...s,materials:s.materials.map(m=>m.id===item.id?schedule(m,ok):m),recallCorrect:s.recallCorrect+(ok?1:0),recallWrong:s.recallWrong+(ok?0:1),daily:{...s.daily,recall:true}}));setAnswer("");setRevealed(false);setRecallIndex(i=>i+1)}
 async function send(e:FormEvent){e.preventDefault();if(!message.trim()||busy)return;const text=message.trim();setMessage("");setChat(c=>[...c,{role:"user",text}]);setBusy(true);try{const r=await fetch("/api/tutor",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text,history:chat,minutes:quick?5:10,immersionLevel:state.target==="A0"?1:state.target==="A1"?2:state.target==="A2"?3:4,knownWords:known,weakWords:weak,focusWords:state.materials.slice(-12).map(x=>x.dutch),commonMistakes:state.mistakes,courseLed:true})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Tutor error");setChat(c=>[...c,{role:"assistant",text:d.reply,translation:d.translation,correction:d.correction||undefined}]);setState(s=>({...s,conversationTurns:s.conversationTurns+1,daily:{...s.daily,speak:true,speakingMinutes:s.daily.speakingMinutes+1},mistakes:d.correction?[...s.mistakes,{wrong:d.correction.wrong,correct:d.correction.better,why:d.correction.why,count:1}].slice(-30):s.mistakes}));}catch(err){setChat(c=>[...c,{role:"assistant",text:err instanceof Error?err.message:"Tutor error"}])}finally{setBusy(false)}}
 function startSpeak(){setTab("speak");if(!chat.length)setChat([{role:"assistant",text:known.length?"Hoi! Laten we oefenen met wat je al hebt geleerd. Vertel iets eenvoudigs over vandaag.":"Hoi! Complete your first Kim lesson, record what you learned, then we’ll practice it here.",translation:known.length?"Hi! Let's practice what you've already learned. Tell me something simple about today.":undefined}])}
 function mic(){const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){alert("Voice input is not supported in this browser. You can still use your keyboard microphone.");return}const r=new SR();r.lang="nl-NL";r.onresult=(e:any)=>setMessage(e.results[0][0].transcript);r.start()}
 const accuracy=Math.round(state.recallCorrect/Math.max(1,state.recallCorrect+state.recallWrong)*100);const active=state.materials.filter(x=>x.strength>=3).length;
 if(!loaded)return null;
 return <main className="shell"><header className="header"><div><div className="brand">Dutch Learning 🇳🇱</div><div className="subtle">Course → recall → speak → immersion</div></div><span className="badge">{state.target}</span></header>
 {tab==="today"&&<div className="stack"><section className="card hero"><div className="kicker">DUTCH TODAY</div><h1>{quick?"Quick Dutch":"Learn it. Keep it. Use it."}</h1><div className="progressBar"><span style={{width:`${done*25}%`}}/></div><div className="subtle">{done}/4 parts complete today · {due.length} reviews due</div><button className="secondary" onClick={()=>setQuick(q=>!q)} style={{marginTop:12}}>{quick?"Show full routine":"Busy day? Quick Dutch"}</button></section>
 {quick?<><Task checked={state.daily.recall} title="RECALL" time="5 min" text="Spaced active recall of material you have learned." action={()=>setTab("recall")}/><Task checked={state.daily.speak} title="SPEAK" time="5 min" text="Use remembered Dutch in conversation." action={startSpeak}/></>:<><Task checked={state.daily.learn} title="LEARN" time="15–20 min" text="Continue your next Learn Dutch with Kim / Dutchies to Be lesson in order." action={()=>setTab("course")}/><Task checked={state.daily.recall} title="RECALL" time="5 min" text="Active recall from today AND older lessons." action={()=>setTab("recall")}/><Task checked={state.daily.speak} title="SPEAK" time="5–10 min" text="Conversation built around material you have actually learned." action={startSpeak}/><Task checked={state.daily.immersion} title="IMMERSION" time="20–60+ min" text="Dutch in your ears while walking, eating, or getting ready." action={()=>setTab("immerse")}/></>}</div>}
 {tab==="course"&&<div className="stack"><section className="card"><div className="kicker">STRUCTURED CURRICULUM</div><h2 className="noTopish">Learn Dutch with Kim</h2><p className="subtle">The app does not choose your next lesson. Work through Kim’s curriculum in order, then record what you learned here.</p><a className="primary linkButton" href="https://www.youtube.com/@learndutchwithkim" target="_blank" rel="noreferrer">Open YouTube course ↗</a></section><form className="card stack" onSubmit={saveLesson}><h3 className="noTop">Record completed lesson</h3><input className="bigInput" placeholder="Video / lesson title" value={lesson.title} onChange={e=>setLesson({...lesson,title:e.target.value})}/><input className="bigInput" placeholder="Paste YouTube link (optional)" value={lesson.url} onChange={e=>setLesson({...lesson,url:e.target.value})}/><select className="bigInput" value={lesson.level} onChange={e=>setLesson({...lesson,level:e.target.value as Level})}>{["A0","A1","A2","B1","B2"].map(x=><option key={x}>{x}</option>)}</select><textarea className="bigInput" placeholder={'Vocabulary — one per line, ideally: Dutch = English\nwaar = where'} value={lesson.vocab} onChange={e=>setLesson({...lesson,vocab:e.target.value})}/><textarea className="bigInput" placeholder="Useful phrases — Dutch = English" value={lesson.phrases} onChange={e=>setLesson({...lesson,phrases:e.target.value})}/><textarea className="bigInput" placeholder="Grammar / sentence structures learned" value={lesson.grammar} onChange={e=>setLesson({...lesson,grammar:e.target.value})}/><textarea className="bigInput" placeholder="What did you struggle with?" value={lesson.struggles} onChange={e=>setLesson({...lesson,struggles:e.target.value})}/><label className="subtle">Confidence: {lesson.confidence}/5<input type="range" min="1" max="5" value={lesson.confidence} onChange={e=>setLesson({...lesson,confidence:Number(e.target.value)})}/></label><button className="primary">Save lesson + schedule reviews</button></form><section className="card"><h3 className="noTop">Completed lessons</h3>{!state.lessons.length?<p className="subtle">Your first recorded Kim lesson will appear here.</p>:state.lessons.slice().reverse().map(l=><div className="mistake" key={l.id}><strong>{l.title}</strong><small>{l.level} · {l.date} · confidence {l.confidence}/5</small></div>)}</section></div>}
 {tab==="recall"&&<div className="stack"><section className="card"><div className="kicker">SPACED ACTIVE RECALL</div><h2 className="noTopish">{due.length?`${due.length} due today`:"You're caught up"}</h2><p className="subtle">Answers stay hidden until you attempt retrieval. Missed material returns sooner; strong material gets longer intervals.</p></section>{item?<section className="card recallCard"><div className="badge">{item.kind}</div><h2>{item.english?`How would you say: ${item.english}?`:`Recall this ${item.kind} from lesson ${state.lessons.find(l=>l.id===item.lessonId)?.title||"your course"}.`}</h2><input className="bigInput" value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Produce the Dutch from memory…"/><button className="primary" disabled={!answer.trim()} onClick={()=>setRevealed(true)}>Check / reveal</button>{revealed&&<div className="success"><strong>Target: {item.dutch}</strong>{answer&&<div>Your answer: {answer}</div>}<div className="subtle" style={{marginTop:6}}>Did you retrieve the meaning and structure without peeking?</div><div className="row"><button className="secondary" onClick={()=>grade(false)}>Missed / needed help</button><button className="secondary" onClick={()=>grade(norm(answer)===norm(item.dutch)||confirm("Count this as correct?"))}>Got it</button></div></div>}</section>:<section className="card"><strong>No reviews due right now.</strong><p className="subtle">Record another course lesson or come back when your next spaced review is due.</p></section>}</div>}
 {tab==="speak"&&<div className="stack"><section className="card"><div className="kicker">CONVERSATION</div><strong>Use what you know</strong><p className="subtle">The tutor receives your learned material, weak items, and recurring mistakes. It should mostly stay inside that boundary and make you construct answers.</p></section><div className="chat">{chat.map((m,i)=><div key={i}><div className={`bubble ${m.role==="user"?"user":"tutor"}`}>{m.text}</div>{m.translation&&<div className="helper">{m.translation}</div>}{m.correction&&<div className="correction"><strong>Repair:</strong> {m.correction.better}<small>{m.correction.why}</small></div>}</div>)}</div><form className="composer" onSubmit={send}><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Answer in Dutch — English only if stuck…"/><button type="button" className="iconButton mic" onClick={mic}>🎙</button><button className="iconButton" disabled={busy}>↑</button></form></div>}
 {tab==="immerse"&&<div className="stack"><section className="card"><div className="kicker">IMMERSION</div><h2 className="noTopish">Dutch in your ears</h2><p className="subtle">Supplemental listening only. It never advances your structured course level.</p><div className="row"><button className="secondary" onClick={()=>dailyPatch({immersion:true,listeningMinutes:state.daily.listeningMinutes+20})}>+20 min listened</button><strong>{state.daily.listeningMinutes} min today</strong></div></section><form className="card stack" onSubmit={e=>{e.preventDefault();if(!immerse.title)return;setState(s=>({...s,immersion:[...s.immersion,{id:`im-${Date.now()}`,title:immerse.title,url:immerse.url,level:immerse.level,favorite:false,listened:false,minutes:0}]}));setImmerse({title:"",url:"",level:immerse.level})}}><h3 className="noTop">Save listening content</h3><input className="bigInput" placeholder="Title" value={immerse.title} onChange={e=>setImmerse({...immerse,title:e.target.value})}/><input className="bigInput" placeholder="YouTube link" value={immerse.url} onChange={e=>setImmerse({...immerse,url:e.target.value})}/><select className="bigInput" value={immerse.level} onChange={e=>setImmerse({...immerse,level:e.target.value as any})}>{["A0","A1","A2","B1","Natural"].map(x=><option key={x}>{x}</option>)}</select><button className="primary">Save</button></form>{["A0","A1","A2","B1","Natural"].map(level=><section className="card" key={level}><h3 className="noTop">{level}</h3>{state.immersion.filter(x=>x.level===level).map(x=><div className="wordRow" key={x.id}><div><strong>{x.title}</strong><div className="subtle">{x.listened?"Listened":"Not listened yet"}</div></div><div>{x.url&&<a href={x.url} target="_blank" rel="noreferrer">Open ↗</a>} <button className="textButton" onClick={()=>setState(s=>({...s,immersion:s.immersion.map(y=>y.id===x.id?{...y,listened:true}:y),daily:{...s.daily,immersion:true}}))}>✓</button></div></div>)}</section>)}</div>}
 {tab==="progress"&&<div className="stack"><section className="card"><div className="kicker">LONG-TERM PROGRESS</div><h2 className="noTopish">A0 → A1 → A2 → B1 → B2</h2><select className="bigInput" value={state.target} onChange={e=>setState(s=>({...s,target:e.target.value as Level}))}>{["A0","A1","A2","B1","B2"].map(x=><option key={x}>{x}</option>)}</select></section><div className="stats"><Stat n={state.lessons.length} t="Lessons completed"/><Stat n={active} t="Actively remembered"/><Stat n={state.materials.length-active} t="Still learning"/><Stat n={`${accuracy}%`} t="Recall accuracy"/><Stat n={state.conversationTurns} t="Speaking turns"/><Stat n={state.daily.listeningMinutes} t="Listening min today"/></div><section className="card"><h3 className="noTop">Frequently missed</h3>{state.materials.filter(x=>x.wrong>0).sort((a,b)=>b.wrong-a.wrong).slice(0,10).map(x=><div className="scoreRow" key={x.id}><span>{x.dutch}</span><strong>{x.wrong} misses</strong></div>)}</section></div>}
 <nav className="nav nav6">{(["today","course","recall","speak","immerse","progress"] as Tab[]).map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x==="today"?"Today":x[0].toUpperCase()+x.slice(1)}</button>)}</nav></main>
}
function Task({checked,title,time,text,action}:{checked:boolean;title:string;time:string;text:string;action:()=>void}){return <section className="card taskCard" onClick={action}><div className="taskCheck">{checked?"✓":"□"}</div><div><div className="row"><strong>{title}</strong><span className="badge">{time}</span></div><div className="subtle">{text}</div></div></section>}
function Stat({n,t}:{n:string|number;t:string}){return <div className="stat"><strong>{n}</strong><span>{t}</span></div>}
