"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";

type Tab = "home" | "learn" | "review" | "quiz" | "progress";
type Stage = "teach" | "review" | "conversation";
type ActiveMode = "learn" | "quiz";
type TeachPhase = "study" | "recall";
type Correction = { wrong: string; better: string; why: string; clue?: string };
type LearnedChunk = { dutch: string; english: string; pronunciation: string };
type ChatMessage = { role: "assistant" | "user"; text: string; translation?: string; hint?: string; correction?: Correction; retryRequired?: boolean };
type VocabularyWord = { id: string; dutch: string; english: string; pronunciation: string; mastery: number; correctRecall: number; wrongRecall: number; correctUse: number; wrongUse: number; nextReview: string; lastSeen?: string };
type CanDo = { label: string; status: "can" | "working" | "later" };
type ProgressState = { version: 3; wordsLearned: number; lastQuiz: number; sessions: number; vocabulary: VocabularyWord[]; recentScores: number[]; commonMistakes: { wrong: string; correct: string; why?: string }[]; canDo: CanDo[] };
type CurriculumItem = LearnedChunk & { id: string; exampleDutch: string; exampleEnglish: string; topic: string };
type QuizQuestion = { id: string; part: 1 | 2 | 3 | 4 | 5; prompt: string; word?: string; tokens?: string[] };
type QuizGrade = { score: number; items: { id: string; correct: boolean; points: number; correction?: string; explanation?: string }[]; coachNote?: string };
type SavedSession = { savedAt: number; activeMode: ActiveMode; minutes: number; stage: Stage; messages: ChatMessage[]; turns: number; pendingRetry: Correction | null; lessonItems: CurriculumItem[]; teachIndex: number; teachPhase: TeachPhase; teachInput: string; teachResult: "correct" | "wrong" | null; reviewQueue: VocabularyWord[]; reviewIndex: number; reviewInput: string; reviewResult: "correct" | "wrong" | null; shownTranslations: Record<number, boolean>; shownHints: Record<number, boolean>; shownAnswers: Record<number, boolean>; quizQuestions: QuizQuestion[]; quizAnswers: Record<string, string>; quizGrade: QuizGrade | null; sessionLearned: LearnedChunk[] };

const PROGRESS_KEY = "dutch-tutor-progress-v3";
const ACTIVE_KEY = "dutch-tutor-active-v3";
const day = (offset = 0) => { const d = new Date(); d.setDate(d.getDate() + offset); return d.toISOString().slice(0, 10); };
const normalize = (s: string) => s.trim().toLocaleLowerCase("nl-NL").replace(/[.!?,]/g, "").replace(/\s+/g, " ");
const uid = () => Math.random().toString(36).slice(2, 10);
const cleanDisplay = (s: string) => s.replace(/\*\*/g, "");

const STARTER_WORDS: VocabularyWord[] = [
  { id: "denken", dutch: "denken", english: "to think", pronunciation: "DEN-ken", mastery: 42, correctRecall: 3, wrongRecall: 4, correctUse: 1, wrongUse: 2, nextReview: day(0) },
  { id: "geven", dutch: "geven", english: "to give", pronunciation: "GHAY-ven", mastery: 40, correctRecall: 2, wrongRecall: 4, correctUse: 1, wrongUse: 2, nextReview: day(0) },
  { id: "geld", dutch: "geld", english: "money", pronunciation: "khelt", mastery: 38, correctRecall: 2, wrongRecall: 5, correctUse: 0, wrongUse: 2, nextReview: day(0) },
  { id: "telefoon", dutch: "telefoon", english: "phone", pronunciation: "tay-luh-FOHN", mastery: 54, correctRecall: 4, wrongRecall: 3, correctUse: 1, wrongUse: 1, nextReview: day(0) },
  { id: "studeren", dutch: "studeren", english: "to study", pronunciation: "stuu-DAY-ren", mastery: 68, correctRecall: 7, wrongRecall: 2, correctUse: 5, wrongUse: 2, nextReview: day(2) },
  { id: "vandaag", dutch: "vandaag", english: "today", pronunciation: "van-DAAKH", mastery: 72, correctRecall: 8, wrongRecall: 2, correctUse: 5, wrongUse: 1, nextReview: day(3) },
  { id: "wonen", dutch: "wonen", english: "to live", pronunciation: "WOH-nen", mastery: 65, correctRecall: 6, wrongRecall: 2, correctUse: 4, wrongUse: 2, nextReview: day(1) },
  { id: "moe", dutch: "moe", english: "tired", pronunciation: "moo", mastery: 74, correctRecall: 7, wrongRecall: 1, correctUse: 5, wrongUse: 1, nextReview: day(4) },
];

const CORE: CurriculumItem[] = [
  { id:"ik-ben", dutch:"ik ben", english:"I am", pronunciation:"ik ben", exampleDutch:"Ik ben student.", exampleEnglish:"I am a student.", topic:"core" },
  { id:"ik-heb", dutch:"ik heb", english:"I have", pronunciation:"ik hep", exampleDutch:"Ik heb vandaag les.", exampleEnglish:"I have class today.", topic:"core" },
  { id:"ik-ga", dutch:"ik ga", english:"I go / I am going", pronunciation:"ik kha", exampleDutch:"Ik ga naar de les.", exampleEnglish:"I am going to class.", topic:"core" },
  { id:"ik-doe", dutch:"ik doe", english:"I do", pronunciation:"ik doo", exampleDutch:"Ik doe mijn huiswerk.", exampleEnglish:"I do my homework.", topic:"core" },
  { id:"ik-wil", dutch:"ik wil", english:"I want", pronunciation:"ik vil", exampleDutch:"Ik wil Nederlands leren.", exampleEnglish:"I want to learn Dutch.", topic:"core" },
  { id:"ik-kan", dutch:"ik kan", english:"I can", pronunciation:"ik kan", exampleDutch:"Ik kan een beetje Nederlands spreken.", exampleEnglish:"I can speak a little Dutch.", topic:"core" },
  { id:"ik-moet", dutch:"ik moet", english:"I have to / must", pronunciation:"ik moot", exampleDutch:"Ik moet straks trainen.", exampleEnglish:"I have to train later.", topic:"core" },
  { id:"ik-vind", dutch:"ik vind", english:"I think / I find", pronunciation:"ik fint", exampleDutch:"Ik vind Nederlands leuk.", exampleEnglish:"I think Dutch is fun.", topic:"opinions" },
  { id:"ik-denk", dutch:"ik denk", english:"I think", pronunciation:"ik denk", exampleDutch:"Ik denk van wel.", exampleEnglish:"I think so.", topic:"opinions" },
  { id:"ik-weet", dutch:"ik weet", english:"I know", pronunciation:"ik vayt", exampleDutch:"Ik weet het niet.", exampleEnglish:"I don't know.", topic:"core" },
  { id:"ik-begrijp", dutch:"ik begrijp het niet", english:"I don't understand", pronunciation:"ik buh-KHRIPE ut neet", exampleDutch:"Sorry, ik begrijp het niet.", exampleEnglish:"Sorry, I don't understand.", topic:"survival" },
  { id:"wat-betekent", dutch:"wat betekent ...?", english:"what does ... mean?", pronunciation:"vat buh-TAY-kent", exampleDutch:"Wat betekent 'straks'?", exampleEnglish:"What does 'straks' mean?", topic:"survival" },
  { id:"herhalen", dutch:"kun je dat herhalen?", english:"can you repeat that?", pronunciation:"kun yuh dat hair-HAH-len", exampleDutch:"Sorry, kun je dat herhalen?", exampleEnglish:"Sorry, can you repeat that?", topic:"survival" },
  { id:"hoe-gaat", dutch:"hoe gaat het?", english:"how are you?", pronunciation:"hoo khaat ut", exampleDutch:"Hoi! Hoe gaat het?", exampleEnglish:"Hi! How are you?", topic:"conversation" },
  { id:"gaat-goed", dutch:"het gaat goed", english:"I'm doing well", pronunciation:"ut khaat khoot", exampleDutch:"Het gaat goed, dank je.", exampleEnglish:"I'm doing well, thank you.", topic:"conversation" },
  { id:"waar-ben", dutch:"waar ben je?", english:"where are you?", pronunciation:"vaar ben yuh", exampleDutch:"Waar ben je nu?", exampleEnglish:"Where are you now?", topic:"questions" },
  { id:"wat-doe", dutch:"wat doe je?", english:"what are you doing?", pronunciation:"vat doo yuh", exampleDutch:"Wat doe je vandaag?", exampleEnglish:"What are you doing today?", topic:"questions" },
  { id:"waar-ga", dutch:"waar ga je naartoe?", english:"where are you going?", pronunciation:"vaar kha yuh NAHR-too", exampleDutch:"Waar ga je naartoe?", exampleEnglish:"Where are you going?", topic:"questions" },
  { id:"wanneer", dutch:"wanneer", english:"when", pronunciation:"vah-NAIR", exampleDutch:"Wanneer ga je trainen?", exampleEnglish:"When are you going to train?", topic:"questions" },
  { id:"waarom", dutch:"waarom", english:"why", pronunciation:"VAH-rom", exampleDutch:"Waarom leer je Nederlands?", exampleEnglish:"Why are you learning Dutch?", topic:"questions" },
  { id:"omdat", dutch:"omdat", english:"because", pronunciation:"om-DAT", exampleDutch:"Ik leer Nederlands omdat ik het leuk vind.", exampleEnglish:"I learn Dutch because I like it.", topic:"connectors" },
  { id:"en", dutch:"en", english:"and", pronunciation:"en", exampleDutch:"Ik studeer en ik train.", exampleEnglish:"I study and I train.", topic:"connectors" },
  { id:"maar", dutch:"maar", english:"but", pronunciation:"mahr", exampleDutch:"Ik ben moe, maar het gaat goed.", exampleEnglish:"I am tired, but I'm doing well.", topic:"connectors" },
  { id:"ook", dutch:"ook", english:"also", pronunciation:"ohk", exampleDutch:"Ik leer ook Nederlands.", exampleEnglish:"I also learn Dutch.", topic:"connectors" },
  { id:"nu", dutch:"nu", english:"now", pronunciation:"new", exampleDutch:"Ik ben nu thuis.", exampleEnglish:"I am home now.", topic:"time" },
  { id:"straks", dutch:"straks", english:"later / in a little while", pronunciation:"strahks", exampleDutch:"Ik ga straks trainen.", exampleEnglish:"I am going to train later.", topic:"time" },
  { id:"morgen", dutch:"morgen", english:"tomorrow", pronunciation:"MOR-khen", exampleDutch:"Morgen heb ik les.", exampleEnglish:"Tomorrow I have class.", topic:"time" },
  { id:"gisteren", dutch:"gisteren", english:"yesterday", pronunciation:"KHIS-ter-en", exampleDutch:"Gisteren had ik training.", exampleEnglish:"Yesterday I had practice.", topic:"time" },
  { id:"les", dutch:"de les", english:"class / lesson", pronunciation:"duh les", exampleDutch:"Ik ga naar de les.", exampleEnglish:"I am going to class.", topic:"college" },
  { id:"huiswerk", dutch:"huiswerk", english:"homework", pronunciation:"HOWS-vairk", exampleDutch:"Ik doe mijn huiswerk.", exampleEnglish:"I do my homework.", topic:"college" },
  { id:"training", dutch:"training", english:"practice / training", pronunciation:"TRAY-ning", exampleDutch:"Ik heb vanmiddag training.", exampleEnglish:"I have practice this afternoon.", topic:"track" },
  { id:"trainen", dutch:"trainen", english:"to train / practice", pronunciation:"TRAY-nen", exampleDutch:"Ik ga straks trainen.", exampleEnglish:"I am going to practice later.", topic:"track" },
  { id:"eten", dutch:"eten", english:"to eat", pronunciation:"AY-ten", exampleDutch:"Ik ga nu eten.", exampleEnglish:"I am going to eat now.", topic:"daily" },
  { id:"drinken", dutch:"drinken", english:"to drink", pronunciation:"DRING-ken", exampleDutch:"Ik drink water.", exampleEnglish:"I drink water.", topic:"daily" },
  { id:"slapen", dutch:"slapen", english:"to sleep", pronunciation:"SLAH-pen", exampleDutch:"Ik wil slapen.", exampleEnglish:"I want to sleep.", topic:"daily" },
  { id:"leuk", dutch:"leuk", english:"fun / nice", pronunciation:"lurk", exampleDutch:"Dat is leuk.", exampleEnglish:"That is fun.", topic:"descriptions" },
  { id:"goed", dutch:"goed", english:"good / well", pronunciation:"khoot", exampleDutch:"Dat klinkt goed.", exampleEnglish:"That sounds good.", topic:"descriptions" },
  { id:"blij", dutch:"blij", english:"happy", pronunciation:"bligh", exampleDutch:"Ik ben blij.", exampleEnglish:"I am happy.", topic:"feelings" },
  { id:"druk", dutch:"druk", english:"busy", pronunciation:"druk", exampleDutch:"Ik ben vandaag druk.", exampleEnglish:"I am busy today.", topic:"feelings" },
  { id:"honger", dutch:"ik heb honger", english:"I am hungry", pronunciation:"ik hep HONG-er", exampleDutch:"Ik heb honger na de training.", exampleEnglish:"I am hungry after practice.", topic:"daily" },
];

const OPENERS = [
  { text:"Hoi Calvin! Hoe gaat het vandaag?", translation:"Hi Calvin! How are you today?", hint:"Try: Het gaat ..." },
  { text:"Hoi! Waar ben je nu?", translation:"Hi! Where are you now?", hint:"Try: Ik ben ..." },
  { text:"Wat ga je straks doen?", translation:"What are you going to do later?", hint:"Try: Ik ga ..." },
  { text:"Heb je vandaag les?", translation:"Do you have class today?", hint:"Try: Ja, ik heb ... / Nee, ..." },
  { text:"Wat wil je vanavond doen?", translation:"What do you want to do tonight?", hint:"Try: Ik wil ..." },
  { text:"Wanneer ga je vandaag trainen?", translation:"When are you going to train today?", hint:"Try: Ik ga ... trainen." },
  { text:"Wat vind je leuk aan Nederlands?", translation:"What do you like about Dutch?", hint:"Try: Ik vind ... leuk." },
  { text:"Ben je vandaag druk of rustig?", translation:"Are you busy or relaxed today?", hint:"Try: Ik ben ..." },
];

const DEFAULT_PROGRESS: ProgressState = { version:3, wordsLearned:130, lastQuiz:70, sessions:6, vocabulary:STARTER_WORDS, recentScores:[82,76,70], commonMistakes:[{ wrong:"Ik ben studeer.", correct:"Ik studeer.", why:"Do not use ben before a conjugated verb here." }], canDo:[{label:"Introduce yourself",status:"can"},{label:"Say how you are doing",status:"can"},{label:"Talk about what you are doing today",status:"working"},{label:"Talk about tomorrow",status:"working"},{label:"Ask for clarification in Dutch",status:"working"},{label:"Tell a short story in the past",status:"later"}] };

const FALLBACK_QUIZ: QuizQuestion[] = [
  {id:"v1",part:1,prompt:"I have",word:"ik heb"},{id:"v2",part:1,prompt:"I want",word:"ik wil"},{id:"v3",part:1,prompt:"homework",word:"huiswerk"},
  {id:"d1",part:2,prompt:"I have class today."},{id:"d2",part:2,prompt:"I want to learn Dutch."},
  {id:"e1",part:3,prompt:"Ik ga straks trainen."},{id:"e2",part:3,prompt:"Ik ben moe, maar ik ben blij."},
  {id:"b1",part:4,prompt:"Build: Tomorrow I am going to class.",tokens:["morgen","ga","ik","naar","de","les","ben","goed"]},
  {id:"c1",part:5,prompt:"Wat ga je straks doen? Answer naturally in Dutch."}
];

function migrateProgress(): ProgressState {
  try {
    const v3 = localStorage.getItem(PROGRESS_KEY); if (v3) return { ...DEFAULT_PROGRESS, ...JSON.parse(v3), version:3 };
    const v2 = localStorage.getItem("dutch-tutor-progress-v2");
    if (v2) { const p = JSON.parse(v2); return { ...DEFAULT_PROGRESS, ...p, version:3, vocabulary:Array.isArray(p.vocabulary)&&p.vocabulary.length?p.vocabulary:STARTER_WORDS } as ProgressState; }
  } catch {}
  return DEFAULT_PROGRESS;
}

function starterFor(session: number): ChatMessage[] { const o = OPENERS[session % OPENERS.length]; return [{ role:"assistant", text:o.text, translation:o.translation, hint:o.hint }]; }
function daysUntilChristmas() { const now=new Date(); let xmas=new Date(now.getFullYear(),11,25); if (xmas < now) xmas=new Date(now.getFullYear()+1,11,25); return Math.max(0,Math.ceil((xmas.getTime()-now.getTime())/86400000)); }

export default function DutchTutorV3() {
  const [tab,setTab]=useState<Tab>("home"); const [minutes,setMinutes]=useState(10); const [stage,setStage]=useState<Stage>("teach");
  const [progress,setProgress]=useState<ProgressState>(DEFAULT_PROGRESS); const [loaded,setLoaded]=useState(false); const [messages,setMessages]=useState<ChatMessage[]>(starterFor(0));
  const [input,setInput]=useState(""); const [loading,setLoading]=useState(false); const [apiError,setApiError]=useState(""); const [turns,setTurns]=useState(0); const [pendingRetry,setPendingRetry]=useState<Correction|null>(null);
  const [lessonItems,setLessonItems]=useState<CurriculumItem[]>([]); const [teachIndex,setTeachIndex]=useState(0); const [teachPhase,setTeachPhase]=useState<TeachPhase>("study"); const [teachInput,setTeachInput]=useState(""); const [teachResult,setTeachResult]=useState<"correct"|"wrong"|null>(null);
  const [reviewQueue,setReviewQueue]=useState<VocabularyWord[]>([]); const [reviewIndex,setReviewIndex]=useState(0); const [reviewInput,setReviewInput]=useState(""); const [reviewResult,setReviewResult]=useState<"correct"|"wrong"|null>(null);
  const [shownTranslations,setShownTranslations]=useState<Record<number,boolean>>({}); const [shownHints,setShownHints]=useState<Record<number,boolean>>({}); const [shownAnswers,setShownAnswers]=useState<Record<number,boolean>>({});
  const [quizQuestions,setQuizQuestions]=useState<QuizQuestion[]>(FALLBACK_QUIZ); const [quizAnswers,setQuizAnswers]=useState<Record<string,string>>({}); const [quizGrade,setQuizGrade]=useState<QuizGrade|null>(null); const [quizLoading,setQuizLoading]=useState(false); const [grading,setGrading]=useState(false); const [activeMode,setActiveMode]=useState<ActiveMode|null>(null); const [sessionLearned,setSessionLearned]=useState<LearnedChunk[]>([]);
  const inputRef=useRef<HTMLInputElement>(null);

  useEffect(()=>{ setProgress(migrateProgress()); try { const raw=localStorage.getItem(ACTIVE_KEY); if(raw){ const s=JSON.parse(raw) as SavedSession; if(Date.now()-s.savedAt<7*86400000&&s.activeMode){ setMinutes(s.minutes||10); setStage(s.stage||"teach"); setMessages(s.messages?.length?s.messages:starterFor(0)); setTurns(s.turns||0); setPendingRetry(s.pendingRetry||null); setLessonItems(s.lessonItems||[]); setTeachIndex(s.teachIndex||0); setTeachPhase(s.teachPhase||"study"); setTeachInput(s.teachInput||""); setTeachResult(s.teachResult||null); setReviewQueue(s.reviewQueue||[]); setReviewIndex(s.reviewIndex||0); setReviewInput(s.reviewInput||""); setReviewResult(s.reviewResult||null); setShownTranslations(s.shownTranslations||{}); setShownHints(s.shownHints||{}); setShownAnswers(s.shownAnswers||{}); setQuizQuestions(s.quizQuestions?.length?s.quizQuestions:FALLBACK_QUIZ); setQuizAnswers(s.quizAnswers||{}); setQuizGrade(s.quizGrade||null); setSessionLearned(s.sessionLearned||[]); setActiveMode(s.activeMode); setTab(s.activeMode); } } } catch {} setLoaded(true); },[]);
  useEffect(()=>{ if(loaded) try{localStorage.setItem(PROGRESS_KEY,JSON.stringify(progress))}catch{} },[progress,loaded]);
  useEffect(()=>{ if(!loaded)return; if(!activeMode){try{localStorage.removeItem(ACTIVE_KEY)}catch{};return;} const s:SavedSession={savedAt:Date.now(),activeMode,minutes,stage,messages,turns,pendingRetry,lessonItems,teachIndex,teachPhase,teachInput,teachResult,reviewQueue,reviewIndex,reviewInput,reviewResult,shownTranslations,shownHints,shownAnswers,quizQuestions,quizAnswers,quizGrade,sessionLearned}; try{localStorage.setItem(ACTIVE_KEY,JSON.stringify(s))}catch{} },[loaded,activeMode,minutes,stage,messages,turns,pendingRetry,lessonItems,teachIndex,teachPhase,teachInput,teachResult,reviewQueue,reviewIndex,reviewInput,reviewResult,shownTranslations,shownHints,shownAnswers,quizQuestions,quizAnswers,quizGrade,sessionLearned]);

  const dueWords=useMemo(()=>progress.vocabulary.filter(w=>w.nextReview<=day(0)).sort((a,b)=>a.mastery-b.mastery),[progress.vocabulary]);
  const avgScore=useMemo(()=>Math.round(progress.recentScores.reduce((a,b)=>a+b,0)/Math.max(progress.recentScores.length,1)),[progress.recentScores]);
  const immersionLevel=avgScore>=90&&progress.sessions>=24?4:avgScore>=84&&progress.sessions>=16?3:avgScore>=76&&progress.sessions>=10?2:1;
  const targetTurns=minutes===5?1:minutes===10?3:5; const christmasDays=daysUntilChristmas(); const christmasHours=Math.round(christmasDays*10/60);

  function patchWord(dutch:string,patch:Partial<VocabularyWord>){setProgress(p=>({...p,vocabulary:p.vocabulary.map(w=>normalize(w.dutch)===normalize(dutch)?{...w,...patch}:w)}));}
  function addCurriculum(items:CurriculumItem[]){setProgress(p=>{const v=[...p.vocabulary];let added=0;for(const x of items){if(v.some(w=>normalize(w.dutch)===normalize(x.dutch)))continue;v.push({id:x.id,dutch:x.dutch,english:x.english,pronunciation:x.pronunciation,mastery:15,correctRecall:0,wrongRecall:0,correctUse:0,wrongUse:0,nextReview:day(1),lastSeen:day(0)});added++;}return{...p,vocabulary:v,wordsLearned:p.wordsLearned+added};});}
  function addLearnedWords(items:LearnedChunk[]){if(!items?.length)return;setSessionLearned(p=>{const m=[...p];for(const x of items)if(x?.dutch&&!m.some(y=>normalize(y.dutch)===normalize(x.dutch)))m.push(x);return m.slice(-20)});setProgress(p=>{const v=[...p.vocabulary];let added=0;for(const x of items){if(!x?.dutch||v.some(w=>normalize(w.dutch)===normalize(x.dutch)))continue;v.push({id:uid(),dutch:x.dutch,english:x.english||"",pronunciation:x.pronunciation||"",mastery:20,correctRecall:0,wrongRecall:0,correctUse:0,wrongUse:0,nextReview:day(1),lastSeen:day(0)});added++;}return{...p,vocabulary:v,wordsLearned:p.wordsLearned+added}});}

  function startSession(m:number){if(activeMode&&!window.confirm("Start a new session? Your current session will be replaced."))return; const known=new Set(progress.vocabulary.map(w=>normalize(w.dutch))); const unseen=CORE.filter(x=>!known.has(normalize(x.dutch))); let newCount=m===5?2:m===10?4:6; if(avgScore<55)newCount=Math.max(1,newCount-1); if(immersionLevel>=2)newCount=Math.max(1,newCount-1); const fresh=unseen.slice(0,newCount); const freshSet=new Set(fresh.map(x=>normalize(x.dutch))); const reviewCount=m===5?2:m===10?4:7; const queue=dueWords.filter(w=>!freshSet.has(normalize(w.dutch))).slice(0,reviewCount); addCurriculum(fresh); setMinutes(m);setTurns(0);setPendingRetry(null);setMessages(starterFor(progress.sessions+1));setApiError("");setLessonItems(fresh);setTeachIndex(0);setTeachPhase("study");setTeachInput("");setTeachResult(null);setReviewQueue(queue);setReviewIndex(0);setReviewInput("");setReviewResult(null);setStage(fresh.length?"teach":queue.length?"review":"conversation");setActiveMode("learn");setTab("learn");setShownTranslations({});setShownHints({});setShownAnswers({});setQuizQuestions(FALLBACK_QUIZ);setQuizAnswers({});setQuizGrade(null);setSessionLearned(fresh.map(x=>({dutch:x.dutch,english:x.english,pronunciation:x.pronunciation})));}
  function resumeActive(){if(activeMode)setTab(activeMode);else startSession(10)}
  function finishSession(){setActiveMode(null);setQuizAnswers({});setQuizGrade(null);setSessionLearned([]);setTab("home")}

  const currentLesson=lessonItems[teachIndex];
  function submitTeach(e:FormEvent){e.preventDefault();if(!currentLesson)return;if(teachPhase==="study"){setTeachPhase("recall");setTeachInput("");setTeachResult(null);return;}const ok=normalize(teachInput)===normalize(currentLesson.dutch);setTeachResult(ok?"correct":"wrong");const w=progress.vocabulary.find(x=>normalize(x.dutch)===normalize(currentLesson.dutch));if(w)patchWord(w.dutch,{mastery:Math.max(5,Math.min(100,w.mastery+(ok?8:-5))),correctRecall:w.correctRecall+(ok?1:0),wrongRecall:w.wrongRecall+(ok?0:1),lastSeen:day(0),nextReview:day(ok?2:1)});}
  function nextTeach(){if(teachIndex+1<lessonItems.length){setTeachIndex(i=>i+1);setTeachPhase("study");setTeachInput("");setTeachResult(null)}else{setStage(reviewQueue.length?"review":"conversation");setTeachResult(null);setTimeout(()=>inputRef.current?.focus(),80)}}
  function submitReview(e:FormEvent){e.preventDefault();const w=reviewQueue[reviewIndex];if(!w||reviewResult)return;const ok=normalize(reviewInput)===normalize(w.dutch);setReviewResult(ok?"correct":"wrong");patchWord(w.dutch,{mastery:Math.max(5,Math.min(100,w.mastery+(ok?6:-9))),correctRecall:w.correctRecall+(ok?1:0),wrongRecall:w.wrongRecall+(ok?0:1),lastSeen:day(0),nextReview:day(ok?(w.mastery>=75?7:3):1)});}
  function nextReview(){if(reviewIndex+1>=reviewQueue.length){setStage("conversation");setReviewResult(null);setReviewInput("");setTimeout(()=>inputRef.current?.focus(),80)}else{setReviewIndex(i=>i+1);setReviewResult(null);setReviewInput("")}}

  async function sendMessage(e:FormEvent){e.preventDefault();const text=input.trim();if(!text||loading)return;setInput("");const next=[...messages,{role:"user" as const,text}];setMessages(next);setLoading(true);setApiError("");try{const res=await fetch("/api/tutor",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text,history:next.slice(-14),minutes,immersionLevel,turn:turns+1,knownWords:progress.vocabulary.filter(w=>w.mastery>=55).slice(0,120).map(w=>w.dutch),weakWords:dueWords.slice(0,15).map(w=>w.dutch),focusWords:lessonItems.map(x=>x.dutch),commonMistakes:progress.commonMistakes.slice(0,10),pendingRetry})});const data=await res.json();if(!res.ok)throw new Error(data?.error||"Tutor request failed");const correction=data.correction?.better?data.correction as Correction:undefined;setMessages(p=>[...p,{role:"assistant",text:cleanDisplay(typeof data.reply==="string"?data.reply:"Goed! Vertel me meer."),translation:data.translation,hint:data.hint,correction,retryRequired:Boolean(data.retryRequired)}]);setTurns(t=>t+1);setPendingRetry(data.retryRequired&&correction?correction:null);addLearnedWords(data.learnedChunks||[]);if(correction)setProgress(p=>({...p,commonMistakes:[{wrong:correction.wrong,correct:correction.better,why:correction.why},...p.commonMistakes.filter(m=>m.wrong!==correction.wrong)].slice(0,15)}));else{const used=progress.vocabulary.filter(w=>normalize(text).includes(normalize(w.dutch))&&w.mastery<85);if(used.length)setProgress(p=>({...p,vocabulary:p.vocabulary.map(w=>used.some(u=>u.dutch===w.dutch)?{...w,correctUse:w.correctUse+1,mastery:Math.min(100,w.mastery+2),lastSeen:day(0)}:w)}));}}catch(err){setApiError(err instanceof Error?err.message:"Could not reach the tutor.")}finally{setLoading(false)}}

  function speak(text:string){if(typeof window==="undefined"||!("speechSynthesis"in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(cleanDisplay(text));u.lang="nl-NL";u.rate=.9;const v=window.speechSynthesis.getVoices();u.voice=v.find(x=>x.lang.toLowerCase().startsWith("nl-nl"))||v.find(x=>x.lang.toLowerCase().startsWith("nl"))||null;window.speechSynthesis.speak(u)}
  function startVoice(){if(typeof window==="undefined")return;const w=window as any;const R=w.SpeechRecognition||w.webkitSpeechRecognition;if(!R){setApiError("Voice input is not supported here yet. You can still type.");return;}const r=new R();r.lang="nl-NL";r.interimResults=false;r.maxAlternatives=1;r.onresult=(e:any)=>setInput(e.results?.[0]?.[0]?.transcript||"");r.onerror=()=>setApiError("I couldn't hear that clearly. Try again or type it.");r.start()}

  async function beginQuiz(){if(activeMode==="quiz"&&quizQuestions.length){setTab("quiz");return;}setQuizAnswers({});setQuizGrade(null);setActiveMode("quiz");setTab("quiz");setQuizLoading(true);setApiError("");try{const res=await fetch("/api/quiz/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({level:immersionLevel,minutes,transcript:messages.slice(-16),weakWords:[...progress.vocabulary].sort((a,b)=>a.mastery-b.mastery).slice(0,12).map(w=>({dutch:w.dutch,english:w.english})),learnedChunks:sessionLearned.slice(-10),focusWords:lessonItems.map(x=>({dutch:x.dutch,english:x.english})),commonMistakes:progress.commonMistakes.slice(0,8)})});const data=await res.json();if(!res.ok||!Array.isArray(data.questions)||data.questions.length<5)throw new Error(data?.error||"Could not build adaptive quiz");setQuizQuestions(data.questions)}catch(err){setQuizQuestions(FALLBACK_QUIZ);setApiError(`${err instanceof Error?err.message:"Adaptive quiz unavailable."} Using the built-in quiz instead.`)}finally{setQuizLoading(false)}}
  async function gradeQuiz(e:FormEvent){e.preventDefault();setGrading(true);setQuizGrade(null);setApiError("");try{const res=await fetch("/api/quiz",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({questions:quizQuestions,answers:quizAnswers,level:immersionLevel})});const data=await res.json();if(!res.ok)throw new Error(data?.error||"Could not grade quiz");const grade=data as QuizGrade;setQuizGrade(grade);setProgress(p=>({...p,lastQuiz:grade.score,sessions:p.sessions+1,recentScores:[...p.recentScores,grade.score].slice(-8)}));for(const q of quizQuestions.filter(q=>q.word)){const item=grade.items.find(i=>i.id===q.id);const w=progress.vocabulary.find(x=>normalize(x.dutch)===normalize(q.word||""));if(item&&w)patchWord(w.dutch,{mastery:Math.max(5,Math.min(100,w.mastery+(item.correct?6:-8))),correctRecall:w.correctRecall+(item.correct?1:0),wrongRecall:w.wrongRecall+(item.correct?0:1),nextReview:day(item.correct?3:1)})}}catch(err){setApiError(err instanceof Error?err.message:"Quiz grading failed.")}finally{setGrading(false)}}

  const partTitle=(n:number)=>["","Vocabulary recall","English → Dutch","Dutch → English","Build the sentence","Conversation"][n]; const missed=quizGrade?quizGrade.items.filter(x=>!x.correct&&x.correction):[];

  return <main className="shell">
    <header className="header"><div><div className="brand">Dutch Tutor 🇳🇱</div><div className="subtle">Vocabulary first · then real conversation</div></div><span className="badge">Level {immersionLevel}</span></header>

    {tab==="home"&&<div className="stack">
      <section className="hero card"><div className="kicker">RECOMMENDED DAILY</div><h1>10 focused minutes.</h1><p className="subtle">Learn a few high-frequency chunks, retrieve old ones, use them in guided conversation, then finish with a short quiz.</p><div className="grid3">{[5,10,20].map(m=><button className="timeButton" key={m} onClick={()=>startSession(m)}><strong>{m}</strong><span>min</span></button>)}</div></section>
      {activeMode&&<section className="card"><div className="kicker">SAVED IN PROGRESS</div><strong>{activeMode==="quiz"?"Your quiz is waiting":`${minutes}-minute session · ${stage}`}</strong><p className="subtle">Your place is saved even if you close Safari.</p><button className="primary compact" onClick={resumeActive}>Resume</button></section>}
      <section className="card"><div className="kicker">CHRISTMAS PATH</div><strong>{christmasDays} days · about {christmasHours} focused hours at 10 min/day</strong><p className="subtle">Target: a strong beginner conversational base — understand common questions, build everyday sentences, and handle short real conversations without relying on memorized scripts.</p></section>
      <section className="stats"><div className="stat"><strong>{dueWords.length}</strong><span>due today</span></div><div className="stat"><strong>{progress.vocabulary.length}</strong><span>tracked words/chunks</span></div><div className="stat"><strong>{progress.lastQuiz}%</strong><span>last quiz</span></div><div className="stat"><strong>{avgScore}%</strong><span>recent average</span></div></section>
      <section className="card"><div className="sectionTitle noTop">How Level 1 works</div><p className="subtle">More vocabulary and sentence chunks first, then guided conversation using those exact tools. As your recall becomes automatic, the app gradually shifts toward more Dutch and more spontaneous speaking.</p></section>
    </div>}

    {tab==="learn"&&<div className="stack">
      <section className="card sessionHeader"><div><div className="kicker">{minutes}-MINUTE SESSION</div><strong>{stage==="teach"?`Learn · ${Math.min(teachIndex+1,lessonItems.length)}/${lessonItems.length}`:stage==="review"?`Review · ${Math.min(reviewIndex+1,reviewQueue.length)}/${reviewQueue.length}`:`Conversation · ${Math.min(turns,targetTurns)}/${targetTurns}`}</strong></div><button className="textButton" onClick={beginQuiz}>Finish & quiz</button></section>
      {stage==="teach"&&currentLesson&&<section className="card recallCard"><div className="kicker">NEW HIGH-FREQUENCY CHUNK</div>{teachPhase==="study"?<><h2>{currentLesson.dutch}</h2><div style={{fontSize:18,fontWeight:750}}>{currentLesson.english}</div><p className="subtle">Pronunciation: {currentLesson.pronunciation}</p><div className="success"><strong>{currentLesson.exampleDutch}</strong><br/>{currentLesson.exampleEnglish}</div><div style={{display:"flex",gap:8,marginTop:12}}><button className="secondary" onClick={()=>speak(currentLesson.dutch)}>🔊 Listen</button><button className="primary compact" style={{marginTop:0}} onClick={()=>{setTeachPhase("recall");setTeachInput("");setTeachResult(null)}}>Test me</button></div></>:<form onSubmit={submitTeach}><p className="subtle">Type the Dutch from memory:</p><h2>{currentLesson.english}</h2><input className="bigInput" value={teachInput} onChange={e=>setTeachInput(e.target.value)} autoFocus placeholder="Dutch answer..."/>{teachResult==="wrong"&&<div className="error" style={{marginTop:12}}>Not yet. Correct answer: <strong>{currentLesson.dutch}</strong>. Say it aloud, then type it again.</div>}{teachResult==="correct"&&<div className="success">✓ Correct. Say it aloud once.</div>}{teachResult==="correct"?<button type="button" className="primary" onClick={nextTeach}>Next</button>:<button className="primary">Check</button>}</form>}</section>}

      {stage==="review"&&reviewQueue[reviewIndex]&&<section className="card recallCard"><div className="kicker">SPACED RETRIEVAL</div><p className="subtle">English → Dutch. Produce it without looking.</p><h2>{reviewQueue[reviewIndex].english}</h2><form onSubmit={submitReview}><input className="bigInput" value={reviewInput} onChange={e=>setReviewInput(e.target.value)} autoFocus placeholder="Dutch..."/>{reviewResult==="wrong"&&<div className="error" style={{marginTop:12}}>Correct: <strong>{reviewQueue[reviewIndex].dutch}</strong> · {reviewQueue[reviewIndex].pronunciation}</div>}{reviewResult==="correct"&&<div className="success">✓ Correct</div>}{reviewResult?<button type="button" className="primary" onClick={nextReview}>Next</button>:<button className="primary">Check</button>}</form></section>}

      {stage==="conversation"&&<><div className="coachStrip"><span>🇳🇱 Try Dutch first</span><span>🇺🇸 English fallback is allowed</span><span>🎯 Use today's new chunks</span></div><div className="chat">{messages.map((m,i)=><div key={i}><div className={`bubble ${m.role==="assistant"?"tutor":"user"}`}>{m.text}</div>{m.role==="assistant"&&<><div className="messageTools"><button onClick={()=>speak(m.text)}>🔊 Listen</button><button onClick={()=>setShownTranslations(x=>({...x,[i]:!x[i]}))}>🇺🇸 Translate</button><button onClick={()=>setShownHints(x=>({...x,[i]:!x[i]}))}>💡 Hint</button></div>{shownTranslations[i]&&m.translation&&<div className="helper">{m.translation}</div>}{shownHints[i]&&m.hint&&<div className="helper">{m.hint}</div>}{m.correction&&<div className="correction"><div className="kicker">CORRECTION</div><div className="strike">{m.correction.wrong}</div><p><strong>Hint:</strong> {m.correction.clue||m.hint}</p>{shownAnswers[i]?<><div className="better">{m.correction.better}</div><div className="subtle">{m.correction.why}</div></>:<button className="secondary" onClick={()=>setShownAnswers(x=>({...x,[i]:true}))}>Show corrected sentence</button>}<div className="retryFlag">↻ Try the idea again in Dutch before moving on.</div></div>}</>}</div>)}</div>{apiError&&<div className="error">{apiError}</div>}<form className="composer" onSubmit={sendMessage}><input ref={inputRef} value={input} onChange={e=>setInput(e.target.value)} placeholder="Dutch first — English if stuck..."/><button type="button" className="secondary mic" onClick={startVoice}>🎙️</button><button className="iconButton" disabled={loading}>{loading?"…":"↑"}</button></form>{turns>=targetTurns&&<button className="primary" onClick={beginQuiz}>Conversation complete — take quick quiz</button>}</>}
    </div>}

    {tab==="review"&&<div className="stack"><section className="card"><div className="sectionTitle noTop">Vocabulary & chunks</div><p className="subtle">Weakest and due items come back first. Mastery grows from recall and real sentence use.</p></section><div className="list">{[...progress.vocabulary].sort((a,b)=>(a.nextReview<=day(0)?-1:1)-(b.nextReview<=day(0)?-1:1)||a.mastery-b.mastery).slice(0,60).map(w=><div className="wordRow" key={w.id}><div><div className="word">{w.dutch}</div><div className="subtle">{w.english} · {w.pronunciation}</div><div className="progressBar"><span style={{width:`${w.mastery}%`}}/></div><div className="skillGrid"><span>recall ✓{w.correctRecall} ✗{w.wrongRecall}</span><span>use ✓{w.correctUse}</span><span>{w.nextReview<=day(0)?"due now":`next ${w.nextReview}`}</span></div></div><button className="textButton" onClick={()=>speak(w.dutch)}>🔊</button></div>)}</div></div>}

    {tab==="quiz"&&<div className="stack">{quizLoading?<section className="card">Building a short quiz from today's weak words and new chunks…</section>:<form onSubmit={gradeQuiz}><section className="card"><div className="kicker">QUICK RETRIEVAL QUIZ</div><h2 className="noTopish">No hints. Produce what you know.</h2><p className="subtle">Questions are shorter for a 10-minute session and different across translation sections so one answer does not reveal another.</p>{[1,2,3,4,5].map(part=>{const qs=quizQuestions.filter(q=>q.part===part);if(!qs.length)return null;return <div key={part}><div className="sectionTitle">Part {part} · {partTitle(part)}</div>{qs.map(q=><div className="quizItem" key={q.id}><strong>{q.prompt}</strong>{q.tokens&&<div className="tokens">{q.tokens.map((t,i)=><span key={i}>{t}</span>)}</div>}<input value={quizAnswers[q.id]||""} onChange={e=>setQuizAnswers(a=>({...a,[q.id]:e.target.value}))} placeholder="Your answer..."/>{quizGrade&&(()=>{const g=quizGrade.items.find(i=>i.id===q.id);return g?<div className={`gradeLine ${g.correct?"good":"bad"}`}>{g.correct?"✓ Correct":`✗ ${g.correction||"Incorrect"}`}<small>{g.explanation}</small></div>:null})()}</div>)}</div>})}{apiError&&<div className="error">{apiError}</div>}{!quizGrade?<button className="primary" disabled={grading}>{grading?"Grading…":"Grade quiz"}</button>:<><div className="scoreCard"><div className="score">{quizGrade.score}%</div><p className="subtle">{quizGrade.coachNote}</p></div>{missed.length>0&&<div className="success" style={{textAlign:"left"}}><strong>Notebook recap</strong><br/>Copy the corrections you actually missed, then use them again tomorrow.</div>}<button type="button" className="primary" onClick={finishSession}>Finish session</button></>}</section></form>}</div>}

    {tab==="progress"&&<div className="stack"><section className="stats"><div className="stat"><strong>{progress.vocabulary.length}</strong><span>tracked items</span></div><div className="stat"><strong>{progress.sessions}</strong><span>completed sessions</span></div><div className="stat"><strong>{avgScore}%</strong><span>quiz average</span></div><div className="stat"><strong>{immersionLevel}/4</strong><span>immersion level</span></div></section><section className="card"><div className="sectionTitle noTop">Can-do progress</div>{progress.canDo.map((x,i)=><div className="canDo" key={i}><span>{x.status==="can"?"✓":x.status==="working"?"◐":"○"}</span><span>{x.label}</span><small>{x.status}</small></div>)}</section><section className="card"><div className="sectionTitle noTop">Recent quizzes</div>{progress.recentScores.map((s,i)=><div className="scoreRow" key={i}><span>Quiz {Math.max(1,progress.sessions-progress.recentScores.length+i+1)}</span><strong>{s}%</strong></div>)}</section><section className="card"><div className="sectionTitle noTop">Recurring corrections</div>{progress.commonMistakes.slice(0,8).map((m,i)=><div className="mistake" key={i}><div className="strike">{m.wrong}</div><div className="better">{m.correct}</div><small>{m.why}</small></div>)}</section></div>}

    <nav className="nav"><button className={tab==="home"?"active":""} onClick={()=>setTab("home")}>⌂<br/>Home</button><button className={tab==="learn"?"active":""} onClick={resumeActive}>◉<br/>{activeMode?"Resume":"Learn"}</button><button className={tab==="review"?"active":""} onClick={()=>setTab("review")}>↻<br/>Review</button><button className={tab==="progress"?"active":""} onClick={()=>setTab("progress")}>▥<br/>Progress</button></nav>
  </main>;
}
