import { PageHeader } from "@/components/page-header";
import { mistakes, quizResults } from "@/data/mock-data";

export default function ProgressPage() { return <main className="page safe-top"><PageHeader eyebrow="Your learning" title="Progress" />
  <section className="grid grid-cols-2 gap-3"><div className="card p-5"><p className="text-3xl font-extrabold">130</p><p className="mt-2 text-sm font-bold text-slate-500">Words Learned</p></div><div className="card p-5"><p className="text-2xl font-extrabold">Beginner</p><p className="mt-2 text-sm font-bold text-slate-500">Current Level</p></div></section>
  <section className="mt-8"><h2 className="mb-4 text-xl font-extrabold">Vocabulary</h2><div className="card divide-y divide-slate-100">{[["Strong Words","87","bg-emerald-500"],["Learning","36","bg-amber-400"],["Needs Review","7","bg-[#e8672e]"]].map(([name,count,color]) => <div className="flex items-center justify-between p-5" key={name}><div className="flex items-center gap-3"><span className={`h-3 w-3 rounded-full ${color}`}/><span className="font-bold">{name}</span></div><b>{count}</b></div>)}</div><p className="mt-3 text-sm text-slate-500">Needs review: denken, geven, geld, telefoon</p></section>
  <section className="mt-8"><h2 className="mb-4 text-xl font-extrabold">Recent quiz scores</h2><div className="card p-5"><div className="flex h-36 items-end justify-around gap-4">{quizResults.map(q => <div className="flex h-full flex-1 flex-col justify-end text-center" key={q.id}><b className="mb-2 text-sm">{q.score}%</b><div className="mx-auto w-10 rounded-t-lg bg-[#162640]" style={{height:`${q.score}%`}}/><span className="mt-2 text-xs font-bold text-slate-500">{q.lesson.replace("Lesson ","L")}</span></div>)}</div></div></section>
  <section className="mt-8"><h2 className="mb-4 text-xl font-extrabold">Common Mistakes</h2><div className="space-y-3">{mistakes.map(m => <article className="card p-5" key={m.id}><span className="eyebrow">{m.category}</span><div className="mt-4 grid grid-cols-[4rem_1fr] gap-y-3 text-sm"><b className="text-red-600">Incorrect</b><span>{m.incorrect}</span><b className="text-emerald-700">Correct</b><span className="font-bold">{m.correct}</span></div><p className="mt-4 text-sm leading-relaxed text-slate-500">{m.explanation}</p></article>)}</div></section>
  </main>; }
